RocketChat/Rocket.Chat.iOS

LoadMoreHeaderTableViewCell.swift
NoDetailsTableViewCell.swift
Rocket.Chat.iOS.xcodeproj/project.pbxproj
Rocket.Chat.iOS/Base.lproj/Main.storyboard
ViewController.swift

changed noDetailsTableViewCell to NoDetailsTableViewCell

changed loadMoreHeaderTableViewCell to LoadMoreHeaderTableViewCell

---

Rocket.Chat.iOS.xcodeproj/project.pbxproj
Rocket.Chat.iOS/Base.lproj/Main.storyboard

Please see commit comments for particular changes included in this PR

Navbar layout

---

README.md

This reverts commit c0804255a27e355073efd2991d5a0928304201ad.

Revert "Add Gitter badge"

---

Rocket.Chat.iOS.xcodeproj/project.pbxproj
Rocket.Chat.iOS/AppDelegate.swift
Rocket.Chat.iOS/Base.lproj/LeftMenu.storyboard
Rocket.Chat.iOS/Base.lproj/Main.storyboard
Rocket.Chat.iOS/ChangeAvatarViewController.swift
Rocket.Chat.iOS/ChooseFileViewController.swift
Rocket.Chat.iOS/FacebookViewController.swift
Rocket.Chat.iOS/GithubViewController.swift
Rocket.Chat.iOS/GoogleViewController.swift
Rocket.Chat.iOS/LinkedInViewController.swift
Rocket.Chat.iOS/UsernameInitialsViewController.swift
Rocket.Chat.iOS/ViewControllers/Auth/AuthViewController.swift
Rocket.Chat.iOS/ViewControllers/Auth/LoginViewController.swift
Rocket.Chat.iOS/ViewControllers/ViewController.swift
Rocket.Chat.iOS/profileViewController.swift

Added avatarControllers group and put in there all the view controllers that will be used for the various ways of setting the avatar. Now all settings UI are completed. 
Also added subscriptions to activeUsers and userData collections. Subscription to userData is to get the username and use it as a placeholder in profile settings. 
Lastly, now the user joins by deafult the default channels after login.
Please review and merge if ok...

Settings UI - Join Default Channels

---

Podfile
Podfile.lock
Rocket.Chat.iOS.xcodeproj/project.pbxproj
Rocket.Chat.iOS/AppDelegate.swift
Rocket.Chat.iOS/ChatMessage.swift
Rocket.Chat.iOS/RoomHistoryManager.swift
Rocket.Chat.iOS/ViewControllers/AccountBarViewController.swift
Rocket.Chat.iOS/ViewControllers/AccountOptionsTableViewController.swift
Rocket.Chat.iOS/ViewControllers/ViewController.swift
Rocket.Chat.iOS/profileViewController.swift

As I said in the previous (closed now) PR, I am not able to create a collection from the client side (using the objectiveDDP library) so I ended up subscribing to messages collection (this is a publication I found on the server code) with the room id and this gives us access to the incoming messages. After logging in the user joins the default channels and gets the 50 last messages. Then I add an observer so we can be notified every time a new message is coming in. The user can also send messages. I imported the swiftyJSON library to handle any JSON. I also added the RoomHistoryManager.swift so later we can implement the server's RoomHistoryManager although there is the possibility we won't need to.
Now we can get the GENERAL's room messages and talk to each other! :)
Please feel free to …

Getting/sending messages from/to the GENERAL room

---

Rocket.Chat.iOS/AppDelegate.swift
Rocket.Chat.iOS/Base.lproj/Main.storyboard
Rocket.Chat.iOS/ViewControllers/Auth/LoginViewController.swift
Rocket.Chat.iOS/ViewControllers/ViewController.swift

This is to keep the user informed about the network status. When loosing the connection a message appears at the top with a spinning indicator. If we loose connection while we are in a chatroom then a message appears at the top, the text input changes to grey background and becomes uneditable and the send button is being disabled.
Please feel free to review...
p.s.>Should this also happen at the register and the forgot password screens?
Note: If you run this on a iphone 5 and earlier, there seems to be a bug. If I turn off my laptop's wifi the simulator doesn't seem to "see" it immediately. If I go to safari (in the simulator) and play around with my laptop's wifi then the simulator "sees" it and after this the app recognises the network connection correctly.

Network Status

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Socket/Response/SocketResponse.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/Storyboards/Chat.storyboard
Rocket.Chat/Views/Cells/Chat/ChatTextCell.swift
Rocket.Chat/Views/Cells/Chat/ChatTextCell.xib
Rocket.ChatTests/Managers/MessageManagerSpec.swift
Rocket.ChatTests/Managers/Socket/ResponseMessageSpec.swift
Rocket.ChatTests/Managers/SocketManagerSpec.swift
Rocket.ChatTests/Models/AuthSpec.swift
Rocket.ChatTests/Models/BaseModelSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift
Rocket.ChatTests/Models/UserSpec.swift

Fetch Messages from Subscription, update list on new messages and more tests 

---

Podfile
Podfile.lock
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/NSDateExtension.swift
Rocket.Chat/Extensions/RealmExtension.swift
Rocket.Chat/Managers/LogManager.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Auth.swift
Rocket.Chat/Views/Cells/Chat/ChatTextCell.xib

A few code improvements

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Model/UserManager.swift

Handle model updates from Realm notifications

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/Auth.swift
Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/Models/User.swift
Rocket.Chat/Storyboards/Chat.storyboard
Rocket.Chat/Views/Cells/Chat/ChatImageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatImageCell.xib
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

This pull-request is doing the initial work of #98.

Add support to viewing images on messages

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Extensions/DateExtension.swift
Rocket.Chat/Extensions/URLExtension.swift

This pull requests resolves #137.

Fixed: invalid URL format on authentication screen

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Chat/ChatTextCell.swift

Fixed: issue when reusing cell for long labels and then short one

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/NibLoadableProtocol.swift
Rocket.Chat/UIViewExtentions.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Avatar/AvatarView.xib
Rocket.Chat/Views/BaseView.swift
Rocket.Chat/Views/Cells/Chat/ChatTextCell.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift

This PR intends to promote `UIView` reusability (through `NibLoadableView` protocol, Autolayout helpers to migrate constraints and a BaseView)
Also it turns off the annoying verbose logging on Xcode, set the env. variable `OS_ACTIVITY_MODE ` to disable.

View reusability

---

Rocket.Chat/Views/Avatar/AvatarView.swift

Fixed: set backgroundColor to clear when loads image

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
HISTORY.md
SECURITY.md

Add contributors files

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

Refresh subscription info on user status changed

---

Podfile.lock
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

update order category subscription name to same desktop version

update order category subscription name

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Extensions/URLExtension.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

Validate server URL by looking into api/info

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.swift
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.xib

Autocomplete usernames when sending a message with "@"

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Localizable.strings
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/Views/Chat/ChatPreviewModeView.swift
Rocket.Chat/Views/Chat/ChatPreviewModeView.xib

Allow user to join Channels

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/RealmExtension.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift

Handle removed & updated subscriptions the right way

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard

Fixed some issues in Search

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Views/Avatar/AvatarView.xib
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.swift
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.xib

Adjustments in autocomplete, support channels & groups

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift

Show Image from cell in full screen on tap

---

.gitignore
Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift

Integrate bugs & socket response errors with Bugsnag

---

Rocket.Chat/Keys.plist

Add empty Keys.plist file

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard

Hide status bar when showing subscriptions list

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
Rocket.Chat/Managers/Launcher/PersistencyCoordinator.swift

Move dependencies out from `AppDelegate`.
Use `NSNotifications` to react to the app lifecycle and reconnect.

AppDelegate clean up

---

.travis.yml
Scripts/build.sh

Bump Xcode version and move build logic to a separated file

---

README.md

Fixed: Swiftlink link in the README file

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Extensions/DateExtension.swift
Rocket.Chat/Extensions/RealmExtension.swift
Rocket.Chat/Extensions/UIImageExtension.swift
Rocket.Chat/Extensions/UILabelExtension.swift
Rocket.Chat/Extensions/UIViewExtentions.swift
Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
Rocket.Chat/Managers/Launcher/UserCoordinator.swift
Rocket.Chat/Managers/Model/UserManager.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift

Fixed: user status offline must be updated too

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: scroll to the correct position when subscription is changed

---

Scripts/swiftlint.sh

add "t" to swiftlint; check for swiftlint instead of "lint"

---

Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Launcher/PersistencyCoordinator.swift
Rocket.Chat/Managers/LogManager.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Models/Base/ModelHandler.swift
Rocket.Chat/Models/Handler/UserModelHandler.swift
Rocket.Chat/Models/Subscription.swift

Some important fixes to the app

---

Rocket.Chat/Info.plist
Rocket.Chat/Managers/LogManager.swift

Fixed: crash on Swift for Release, because optimizations

---

Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Extensions/URLExtension.swift
Rocket.Chat/Localizable.strings
Rocket.Chat/Managers/LogManager.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Rocket.Chat/Managers/Socket/Response/SocketResponse.swift

Handle error message in Auth screen

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Extensions/DataExtension.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Model/UserManager.swift
Rocket.Chat/Managers/PushManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Rocket.Chat.entitlements

Add Remote Notification & send the APN token to server

---

Rocket.Chat/Base.lproj/Main.storyboard
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Storyboards/Chat.storyboard

Use the same loader as web is using

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Extensions/UIImageExtension.swift
Rocket.Chat/Info.plist

Let user send images directly from Camera & compress images from Photo Library

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: iPad crashes when uploading file & menu width on iPads

---

Rocket.Chat/Models/Attachment.swift

Fixed: support viewing GIFs and other external images

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Localizable.strings

Separate unread conversations at the top

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: issues on scroll position when app starts or change conversation

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: invalidate layout of collectionView when device rotates

---

Rocket.Chat/Views/Avatar/AvatarView.swift

Fixed the problem that URL cannot be generated if user name is not English (e.g Korean etc).

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Scripts/swiftlint.sh

Fixed: serious errors from new version of SwiftLint

---

Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Support alias & avatar on Message object

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed scrolling if message is bigger than container layout

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Storyboards/Chat.storyboard

feature added favorite & unfavorite option in the subscription

---

.swiftlint.yml
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Extensions/UIColorCSSColorsExtension.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.xib
Rocket.Chat/Views/Cells/Chat/ChatMessageURLView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageURLView.xib

Add initial support to text box

---

Rocket.Chat/Extensions/URLExtension.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Uploader/UploadManager.swift

Support GridFS & FileSystem to upload files

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift

Improve UX when app has cached messages

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Localizable.strings
Rocket.Chat/Managers/Uploader/Helpers/UploadVideoCompression.swift

This PR adds support to send videos from the app. It also compress the videos before sending it (in the future, it can be a setting in the server).
Closes #252

Support Video Upload

---

Rocket.Chat/Info.plist

Add Provide Export Compliance Information to plist

---

Rocket.Chat/de.lproj/Localizable.strings

Added first german translation

---

Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift

Add initial support to fields field in the attachment object

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/en.lproj/Localizable.strings

Support all basic message types

---

Podfile
Podfile.lock
Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Rocket.Chat-Bridge.h
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Support Markdown in the message text 

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Storyboards/Auth.storyboard

Terms and Policy Privacy in Authentication screen

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Storyboards/Auth.storyboard

Let user to set a new username on login, when user don't have one

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Uploader/Helpers/UploadVideoCompression.swift

Layout bug: keyboard flickers changing subscription

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Animate scrolling from history & new messages

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

Block messages from other users on client-side

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Storyboards/Chat.storyboard

Add "arrow" to scroll down if user isn't in the bottom

---

Rocket.Chat/Models/Attachment.swift

Fixed: file URLs broken

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift
Rocket.ChatTests/Views/AvatarViewSpec.swift

Fixed: crash on avatar initials generation and write tests for it

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: send of empty messages

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Extensions/StringExtensions.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/Storyboards/Chat.storyboard
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoCellProtocol.swift
Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.swift
Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDetailCell.swift
Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
Rocket.Chat/Views/Chat/ChatHeaderViewOffline.swift
Rocket.Chat/Views/Chat/ChatPreviewModeView.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift
Rocket.Chat/Views/Chat/ChatTitleView.xib
Rocket.Chat/Views/Sections/SubscriptionSearchMoreView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift
Rocket.Chat/en.lproj/Localizable.strings

New screen to show details of room, code improvements and more

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist

Fixed: crash on CollectionView data updates

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist

Fixed: app is freezing when loading more messages

---

Podfile
Podfile.lock
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/en.lproj/Localizable.strings

Validate server version and alert user when user tries to connect to it

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerGoogleExtensions.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Views/Avatar/AvatarView.swift

Update project to Xcode 8.3, remove Bugsnag, update all Pods

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Subscriptions/TintedTextField.swift

feat: add clear search button

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Fixed: long press in the cell wasn't working anymore

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift

Add LDAP support on authentication

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift

Fix lint warnings

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/TwoFactorAuthenticationViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Storyboards/Auth.storyboard

[NEW] Add support to 2FA on user login via email or username

---

Rocket.Chat/Info.plist

Update app version to 1.0.6 to new App Store release

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Settings/SettingsViewController.swift
Rocket.Chat/SettingsViewModel.swift
Rocket.ChatTests/SettingsViewModelTests.swift
Rocket.ChatUITests/RocketChatUITests.swift

Refactor Settings and add tests

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/ChatMessageTextViewModel.swift
Rocket.Chat/Extensions/UIViewExtentions.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.ChatTests/ChatMessageTextViewModelTests.swift

Refactor chat message text view and add tests

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Views/Loader/LoaderView.swift
Rocket.ChatTests/Views/LoaderViewSpec.swift

Use the same loader as web

---

Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

feat: properly highlight subscription cell

---

Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

Reverts RocketChat/Rocket.Chat.iOS#407

Revert "feat: properly highlight subscription cell"

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift

Fixed: crash on Logout user

---

Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.ChatTests/Views/AvatarViewSpec.swift

Fixed: crash on avatar with empty username

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/SignupViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Storyboards/Auth.storyboard

Let the user creates an account in the app

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Subscription.swift

Fixed: Realm crash on wrong thread

---

Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthManager.swift

Fixed: Realm crash on auth primarykey duplicated

---

Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

Fixed: crash on channel info invalid subscription

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

Properly highlight subscription cell

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.ChatTests/Managers/MessageManagerSpec.swift
Rocket.ChatTests/Models/AuthSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift
Rocket.ChatTests/Models/UserSpec.swift
Rocket.ChatTests/Views/Chat/ChatDataControllerSpec.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

Show temporary message while sending it

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

Make a few adjustments on the scrolling collectionView to bottom

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Storyboards/Subscriptions.storyboard

Add a cancel button search to the search

---

Rocket.Chat/pt-BR.lproj/Localizable.strings

Translate all missing strings to Portuguese

---

Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Helpers/MessageTextFontAttributes.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/MessageTextCacheManager.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

Cache all markdown processed

---

Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/MessageTextCacheManager.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.xib

Improve the way text quoted messages and replies are displayed

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

Fixed: touch on Links/Phones/Dates in the message text

---

Podfile
Rocket.Chat.SDK/Foobar.swift
Rocket.Chat.SDK/Info.plist
Rocket.Chat.SDK/Rocket.Chat.SDK.h
Rocket.Chat.SDKTests/Info.plist
Rocket.Chat.SDKTests/RocketChatSDKTests.swift
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme

add `Rocket.Chat.SDK` target

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Info.plist

Fixed: app is freezing sometimes

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Info.plist

Fixed some issues, adjusted a few tweaks

---

Rocket.Chat.Shared/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat.Shared/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat.Shared/Controllers/Chat/ChatViewController.swift
Rocket.Chat.Shared/DependencyManager/Injected.swift
Rocket.Chat.Shared/Managers/UploadManager.swift
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/DependencyRepository.swift
Rocket.Chat/Info.plist

@RocketChat/ios-sdk 
Take a look. If it's okay, I'll keep on working on it.

Simple Dependency Injection Attempt

---

Rocket.Chat/de.lproj/Localizable.strings

Update German strings

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.xib

Fixed: offline banner layout is breaking on rotation

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Info.plist

Fixed: crash on subscriptions list out of index

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.ChatTests/Models/MessageURLSpec.swift

I love this product. 
And I want to contribute to solve this issue.
[Set code coverage to 90%+ (and require it for new PRs) · Issue #152 · RocketChat/Rocket.Chat.iOS](https://github.com/RocketChat/Rocket.Chat.iOS/issues/152)

create basis of MessageURLSpec

---

Rocket.Chat/Managers/Model/AuthManager.swift

Fixed: do not ask twice to confirm the login

---

Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Fixed: app truncate some messages

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Fixed: truncated strings in a very few situations

---

Rocket.Chat.SDK/Controllers/SupportViewController.swift
SDKExample/SDKExample/MainViewController.swift

fix: validation alert actions

---

Rocket.Chat/Managers/Socket/SocketManager.swift

Fixed: issue on connecting to a few servers

---

Rocket.Chat.SDK/Controllers/OfflineFormViewController.swift
Rocket.Chat.SDK/Controllers/SupportDepartmentViewController.swift
Rocket.Chat.SDK/Controllers/SupportViewController.swift
Rocket.Chat.SDK/Managers/LiveChatManager.swift
Rocket.Chat.SDK/Models/Department.swift
Rocket.Chat.SDK/Storyboards/Support.storyboard
Rocket.Chat.xcodeproj/project.pbxproj

Offline Forms

---

Rocket.Chat.Shared/Controllers/Chat/ChatDataController.swift
Rocket.Chat.Shared/Controllers/Chat/ChatViewController.swift
Rocket.Chat.Shared/Extensions/DateExtension.swift
Rocket.Chat.Shared/Views/Chat/Cells/ChatMessageBubbleCell.swift
Rocket.Chat.Shared/Views/Chat/Cells/ReceivedMessageBubble.xib
Rocket.Chat.Shared/Views/Chat/Cells/SentMessageBubble.xib

Improve chat interface

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/DateExtension.swift
Rocket.Chat/Extensions/URLExtension.swift
Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
Rocket.Chat/Managers/Launcher/TimestampCoordinator.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/ServerManager.swift
Rocket.ChatTests/Extensions/DateExtensionsSpec.swift

Sync timezone from server to device

---

SDKExample/Podfile

broken path for local dependency

---

Rocket.Chat.Shared/Views/Chat/Cells/ChatMessageBubbleCell.swift

This reverts commit ad38bcf7ae831d17044f05fc55029858b0f93565.
@RocketChat/ios-sdk

Revert "Fixed the width of the cell"

---

Rocket.Chat.Shared/Controllers/Chat/ChatViewController.swift

fix: crashes on the second or later opening of support view controller

---

Podfile
Rocket.Chat.xcodeproj/project.pbxproj
SDKExample/SDKExampleUITests/SDKExampleUITests.swift
Test.Shared/WebSocketMock.swift
Test.Shared/WebSocketMockTests.swift

@RocketChat/ios-sdk 
A feasibility practice

testable WebSocket

---

Rocket.Chat.Shared/Managers/Socket/SocketManager.swift
Test.Shared/WebSocketMock.swift
Test.Shared/WebSocketMockTests.swift

@RocketChat/ios-sdk 
Tests on mock over WebSocket

test: Mocks on SocketManager

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/ChatMessageTextViewModel.swift
Rocket.Chat/Controllers/Chat/ChatControllerDocuments.swift
Rocket.Chat/Controllers/Chat/ChatControllerHeaderStatus.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Helpers/UploadHelper.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/DownloadManager.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Rocket.Chat.entitlements
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.xib
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.xib
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Helpers/UploadHelperSpec.swift
Rocket.ChatTests/Managers/DownloadManagerSpec.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

Closes #552 
This method will allow the user to upload files of any kind from many document apps, such like Dropbox, Google Drive, iCloud and many others.
**1. Select file**
**2. View file being uploaded**
**3. Open file**

[NEW] Support uploading any kind of file, using Document Picker

---

Rocket.Chat.Shared/Extensions/DoubleExtensions.swift
Rocket.Chat.Shared/Extensions/UIColor+RCColors.swift
Rocket.Chat.Shared/Views/Chat/Cells/ChatMessageBubbleCell.swift
Rocket.Chat.Shared/Views/Chat/Cells/ReceivedMessageBubble.xib
Rocket.Chat.Shared/Views/Chat/Cells/SentMessageBubble.xib
Rocket.Chat.xcodeproj/project.pbxproj

[SDK] bubble corner horn

---

Rocket.Chat.Shared/Controllers/Chat/ChatViewController.swift

@RocketChat/ios-sdk 
related commit: cccce1a7158177a3474cc76a88c8bae637364504

Revert: crashes on switching channels

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Remove weird animation on collectionView cells when scrolling to bottom by pressing text box

---

Rocket.Chat.SDK/Controllers/OfflineFormViewController.swift
Rocket.Chat.SDK/Controllers/SupportViewController.swift
Rocket.Chat.SDK/Storyboards/Support.storyboard
Rocket.Chat.Shared/Views/LoaderView.swift

[SDK] UI improvements

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/ArrayExtensions.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Views/Cells/Chat/ChatChannelHeaderCell.swift
Rocket.Chat/Views/Cells/Chat/ChatChannelHeaderCell.xib
Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.xib
Rocket.Chat/Views/Cells/Chat/ChatLoaderCell.swift
Rocket.Chat/Views/Cells/Chat/ChatLoaderCell.xib
Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.xib
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Views/Chat/ChatDataControllerSpec.swift

Closes #591 
Closes #585 
Closes #584

Add loader when loading history and header for start of the conversation

---

README.md

Simply add the store link to README file.

[DOCS] Add store link to README

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist

[FIX] Mark conversation as read when receiving new messages in current chat

---

.github/PULL_REQUEST_TEMPLATE.md

[DOCS] Pull request team on template

---

Rocket.Chat.SDK/Controllers/SupportDepartmentViewController.swift
Rocket.Chat.SDK/Storyboards/Support.storyboard
Rocket.Chat.Shared/Controllers/Chat/ChatViewController.swift
Rocket.Chat.Shared/Views/Chat/Cells/ReceivedMessageBubble.xib
Rocket.Chat.Shared/Views/Chat/Cells/SentMessageBubble.xib

[SDK] Minor UI improvements

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard

Reverts RocketChat/Rocket.Chat.iOS#602

Revert "[NEW] Add user profile picture to the menu on the left"

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj

[UPDATE] Update CocoaPods, Realm and Starscream

---

Rocket.Chat.SDK/Managers/LivechatManager.swift
Rocket.Chat.SDK/Models/Department.swift
Rocket.Chat.Shared/Extensions/UIColor+Hex.swift
Rocket.Chat.Shared/Managers/AuthManager.swift
Rocket.Chat.Shared/Models/Auth.swift
Rocket.Chat.Shared/Views/Chat/Cells/ChatMessageBubbleCell.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.ChatTests/Managers/AuthManagerSpec.swift
SDKExample/SDKExample/AppDelegate.swift

[FIX] Correct some swiftlint issues

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift

[FIX] Remove superfluous lint rule

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

[NEW] Implement sequential (grouped) messages

---

Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Models/Subscription.swift
Rocket.ChatTests/Managers/MessageManagerSpec.swift

[NEW] Support to "hide some types of messages" settings

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.ChatTests/Views/Chat/ChatDataControllerSpec.swift

[REFACTOR] Remove optional from ChatData initializer

---

Podfile
Podfile.lock
Rocket.Chat/Controllers/Chat/ChatControllerDocuments.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Replace URBMediaFocusViewController for SimpleImageViewer

---

README.md

[FIX] Typo in README and remove Codacy badge

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
Rocket.Chat/Managers/Launcher/NetworkCoordinator.swift
Rocket.Chat/Managers/NetworkManager.swift
Rocket.ChatTests/Managers/NetworkManagerSpec.swift

Closes #567
This PR includes the support to open the app when user is offline, read the messages, change servers and everything else that's saved into the local database.

[NEW] Support opening the app when user is offline

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Closes #646
Adjusted an integer literal.

[IMPROVEMENT] Adjust spacing between first message and sequentials

---

Rocket.ChatTests/Managers/NetworkManagerSpec.swift

[FIX] Remove a invalid unit test that runs into race condition

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift

Closes #640 
Also added a test for checking for sequential messages & some minor refactors.

[NEW] Support "groupable" property in Message

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

Closes #658 
Also fixed a warning.

[FIX] Visible cancel button bug

---

Rocket.Chat/Views/Cells/Chat/AutocompleteCell.xib

[FIX] Crash in Autocomplete cell

---

Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift

[FIX] Calculate message height with AttributedString instead of raw text

---

Rocket.Chat/Base.lproj/Main.storyboard
Rocket.Chat/Controllers/MainViewController.swift

[IMPROVEMENT] Open server with local data when can't connect to it

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/TwoFactorAuthenticationViewController.swift

[NEW] Use One-time password automagically from 1Password

---

Rocket.Chat/Controllers/Subscriptions/ServersViewController.swift
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[NEW] Show server options on long-press into the servers list

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift

[FIX] Add multiple instances of the same server

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Helpers/ChatCollectionViewFlowLayout.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/MessageManager.swift

[FIX] Some scrolling issues on Chat, load more messages

---

Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.ChatTests/Extensions/StringExtensionSpec.swift

[FIX] Stuck sometimes when connecting the first time & rare crash in Logout

---

Rocket.Chat/Controllers/Settings/SettingsViewController.swift
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

Closes #681 
I implemented an alert to notify the user if Mail app isn't set and ask the user to do it.

[FIX] Notify the user if Mail app isn't set

---

Rocket.Chat/de.lproj/Localizable.strings

[I18N] Add new German translations

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift

[FIX] Can't connect/add server after connecting to one & backing screen from auth flow

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[FIX] Update titleView data from Subscription when we have some update in database

---

Rocket.Chat/Controllers/Chat/ChatControllerHeaderStatus.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift

[NEW] Show activity indicator when connecting to the server in the status banner

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift

[FIX] Crash on importing file from iPad

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Sometimes, the buttonScrollToBottom doesn't hide

---

Rocket.Chat/Controllers/Subscriptions/ServersViewController.swift

[FIX] Crash on iPad for server long press actions

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Sometimes the view "User is typing" keeps showing forever

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift

[FIX] Keyboard not dismissing when adding existing server

---

Podfile.lock

[FIX] Update SideMenuController with status bar fix

---

Rocket.Chat/Storyboards/Auth.storyboard

[CHORE] Fix typo on server enter screen.

---

Rocket.Chat/Info.plist

[CHORE] Increment app & build version

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.ChatTests/Controllers/ConnectServerViewControllerSpec.swift

[FIX] Tolerate wrong or lack of scheme in connect server view

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Requests/Subscription/SubscriptionMessagesRequest.swift
Rocket.Chat/Controllers/Base/BaseViewController.swift
Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Extensions/DateExtension.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Storyboards/Chat.storyboard
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Controllers/ConnectServerViewControllerSpec.swift
Rocket.ChatTests/Extensions/DateExtensionsSpec.swift

[NEW] List of Pinned and Starred Messages

---

Rocket.Chat/Views/Avatar/AvatarView.swift

[CHORE] Replace substring calls with Swift 4 partial ranges

---

.swiftlint.yml
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Helpers/ChatCollectionViewFlowLayout.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/Response/SocketResponse.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.ChatTests/Managers/MessageManagerSpec.swift

I moved some things around where I could (nested functions and pieces of code that could be their own functions), and I added exceptions where it didn't make sense to touch the code.
Closes #694

[CHORE] Remove all Swift Lint Warnings

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Scroll button not hiding

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsPageViewController.swift

[NEW] Add tap action on page controller's dot to switch page

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[NEW] Add reply message action

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift

[FIX] Updating cache in wrong place causing freezes

---

Rocket.Chat/Info.plist

[RELEASE] Bump app version to 1.6.0 (104)

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Not receiving updates when resubscribing to room

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

[FIX] Time label layout bug

---

Rocket.Chat/Storyboards/Subscriptions.storyboard

[FIX] Server name layout bug

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Views/Chat/ReplyView.swift
Rocket.Chat/Views/Chat/ReplyView.xib

Requires https://github.com/rafaelks/SlackTextViewController/pull/2
Preview:
Closes #737

[NEW] Show nice view when replying/quoting

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

[CHORE] Few adjustments, fixes and debugging code removed from previous PRs

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerGoogleExtensions.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Extensions/StringExtensions.swift
Rocket.Chat/Managers/Launcher/UserCoordinator.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Model/AuthSettingsManager.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Model/UserManager.swift
Rocket.Chat/Managers/PushManager.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.Chat/Models/Base/ModelHandler.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift

[CHORE] Adjust code formatting to swiftlint rules (warnings)

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] App crashing when going back from adding new team

---

Rocket.Chat/Info.plist

[CHORE] Bump app version

---

.github/ISSUE_TEMPLATE.md

[DOCS] Add the name of the apps on the issue template

---

Rocket.Chat/Controllers/Chat/ChatControllerHeaderStatus.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Loader not showing when reconnecting automatically

---

Podfile.lock
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift

[CHORE] Update Realm & RealmSwift to 3.0.0

---

Rocket.Chat/Storyboards/Chat.storyboard

[FIX] A transparent square in the middle of the screen captures the gestures

---

Rocket.Chat/Storyboards/Auth.storyboard

[FIX] Possible spelling error - "User" to "Used"

---

Rocket.Chat/Storyboards/Auth.storyboard

[IMPROVEMENT] Capitalize words for name field on Signup screen

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift

[FIX] Remove duplicated extension in filename of images

---

Rocket.Chat/Info.plist

[CHORE] Bump version to 1.7.0

---

Rocket.Chat/Controllers/Chat/MembersListViewController.swift

[FIX] Blocking scroll in members list, possible crash & title with total

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Managers/LogManager.swift

[FIX] Messages not getting appended to the list

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[IMPROVEMENT] Reduce the time between each call of appendMessages

---

Podfile.lock

[FIX] Use the latest version of our TextViewController pod

---

Rocket.Chat/Models/Attachment.swift

[FIX] Attachments with special characters not opening

---

.hound.yml

@rafaelks You have to add HoundCI Integration to this project. Therefore just go to https://houndci.com/repos, login and click on activate
Closes #806

[CI] Add HoundCI config file

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings

@RocketChat/ios Add French Localizable

[NEW] Add French Localizable

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Models/Base/BaseModel.swift
Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Models/SubscriptionSpec.swift

|Preview|
|-|
|![](https://i.imgur.com/jz0NP6c.jpg?1)|
Closes #848

[FIX] Read-only rooms not being handled correctly

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Helpers/UploadHelper.swift
Rocket.ChatTests/Helpers/UploadHelperSpec.swift

[FIX] GIFs being uploaded and compressed as JPEG

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Main.strings

[i18n] Add Polish localizable

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Possible crash when typing message

---

Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Models/Auth.swift
Rocket.ChatTests/Models/AuthSpec.swift

[FIX] API host not being set properly on resume session

---

Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[FIX] Members list title is wrong for other languages

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[FIX] Bug on search results empty after clearing it

---

Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[FIX] Some i18n strings missing for pt-BR and ge

---

Podfile.lock

[CHORE] Update Fabric, Crashlytics & Realm

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[FIX] Loading forever if a socket error happened in connection

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Prevent appending messages to other subscriptions

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift

[IMPROVEMENT] Performance improvements when the app starts

---

Rocket.Chat/Info.plist

[CHORE] Increment version of the build 1.7.1 (111)

---

Rocket.Chat/en.lproj/Localizable.strings

"We're still working on this feature, stay tunned!"
changed to
"We're still working on this feature, stay tuned!"

[FIX] Typo in work in progress alert

---

Rocket.Chat/de.lproj/Localizable.strings

[i18n] Added translation for "new room" function

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

[FIX] iPhone X on landscape hiding message contents

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[FIX] User being able to send messages when muted

---

Podfile
Podfile.lock
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] iPhone X home bar covering input bar

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[FIX] Add name as secondary sort criteria for some groups

---

Rocket.Chat/ChatMessageTextViewModel.swift
Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/Models/AuthExtensions.swift
Rocket.Chat/Extensions/StringExtensions.swift
Rocket.Chat/Extensions/UIColorCSSColorsExtension.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/MessageURL.swift
Rocket.Chat/Models/Subscription.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift
Rocket.Chat/Views/Form/FormTableViewCell.swift
Rocket.Chat/Views/Sections/SubscriptionSearchMoreView.swift
Rocket.ChatTests/Extensions/StringExtensionSpec.swift

[REFACTOR] Remove all new SwiftLint warnings from the code

---

Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

[FIX] Handle repeated username and channel only once when highlighting

---

README.md
Scripts/test.sh
circle.yml

* Add Post-Test Step to upload Coverage Data to codecov
* Add CircleCI Link to Status Badge
Todo:
@cardoso @rafaelks Please check for correct project configuration within circlci & codecov:
* Activate 'Build forked pull requests' setting in circleci 
Closes #864

[CI][FIX] Codecov badge & file integration

---

Podfile.lock
Rocket.Chat/Controllers/Subscriptions/SubscriptionsPageViewController.swift

[FIX] Fix height of subscriptions list on iphone x

---

Podfile
Podfile.lock

[FIX] HTTP request to Upgrade to WebSocket not working in some cases

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Crash when updating values after they were deleted from data controller

---

Rocket.Chat/Info.plist

[CHORE] Bump version of the app to 1.7.2 (112)

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Managers/Model/PermissionManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Models/Mapping/PermissionModelMapping.swift
Rocket.Chat/Models/Mapping/UserModelMapping.swift
Rocket.Chat/Models/Permission.swift
Rocket.Chat/Models/User.swift
Rocket.Chat/NewRoomViewController.swift
Rocket.Chat/Views/Form/FormTableViewCell.swift
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Controllers/NewRoomViewControllerSpec.swift
Rocket.ChatTests/Managers/PermissionManagerSpec.swift
Rocket.ChatTests/Models/PermissionSpec.swift
Rocket.ChatTests/Models/UserSpec.swift

[NEW] Implement create channel permissions

---

Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Info.plist
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[NEW] Video recording

---

Rocket.Chat/Controllers/Settings/SettingsViewController.swift
Rocket.Chat/NewRoomViewController.swift
Rocket.Chat/SettingsViewModel.swift
Rocket.Chat/Storyboards/Settings.storyboard
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings

Added missing localizable keys/strings for Settings, New Channel controllers, as well as added missing translations for polish localize.

[FIX] Add missing localizable strings

---

Rocket.Chat/fr.lproj/Localizable.strings

Add French translations

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Base.lproj/Main.storyboard
Rocket.Chat/NewRoomViewController.swift
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Main.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[FIX] Missing strings in all languages

---

Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Random crashes when Subscription is nil

---

Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
Rocket.Chat/Models/Message.swift
Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
Rocket.ChatTests/Models/AuthSettingsSpec.swift
Rocket.ChatTests/Models/AuthSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift
Rocket.ChatTests/Models/UserSpec.swift

Made replyString and quoteString computed variables in Message instead of methods in ChatViewController and added tests for them.
Also added some test utilities

[REFACTOR] quoteString and replyString + add tests

---

Podfile
Podfile.lock
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Socket/SocketManager.swift

[FIX] Revert the Starscream update to 2.1.1

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
Rocket.Chat/Controllers/Auth/SignupViewController.swift
Rocket.Chat/Controllers/Auth/TwoFactorAuthenticationViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/ServersViewController.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/DatabaseManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/PushManager.swift
Rocket.Chat/Models/Subscription.swift
Rocket.ChatTests/Managers/AppManagerSpec.swift
Rocket.ChatTests/Managers/DatabaseManagerSpec.swift
Rocket.ChatTests/Managers/PushManagerSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift

This PR aims to: 
- Upgrade our notification handling to the new APIs
- Open correct server and channel when tapping notification
Closes #790

[NEW] Use UserNotifications API & open channel on notification tap

---

README.md

[DOCS] Insert codebeat badge

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Controllers/MainViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/UIWindowExtensions.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Managers/WindowManager.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift
Rocket.Chat/Views/Chat/ChatTitleView.xib
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/Managers/AppManagerSpec.swift

[NEW] Show offline values before even connecting into WebSocket

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[IMPROVEMENT] Make the refresh of data much more smooth & transparent when the app connects to a new server (or starts)

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

[FIX] Data getting mixed between servers 

---

Podfile
Podfile.lock
Rocket.Chat/Info.plist

I also changed the app version to 1.7.3.

[UPDATE] Update Realm, SwiftyJSON & SDWebImage

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift

Caused by #979 in our latest TestFlight build

[HOTFIX] Subscriptions not updating properly (bug in #979)

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Extensions/DateExtension.swift
Rocket.ChatTests/Extensions/DateExtensionsSpec.swift

[FIX] Last day separator sometimes not showing

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/User.swift
Rocket.Chat/Views/Avatar/AvatarView.swift
Rocket.Chat/Views/Avatar/AvatarView.xib
Rocket.ChatTests/Models/AttachmentSpec.swift
Rocket.ChatTests/Models/AuthSettingsSpec.swift
Rocket.ChatTests/Models/AuthSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/MessageURLSpec.swift
Rocket.ChatTests/Models/UserSpec.swift
Rocket.ChatTests/Views/AvatarViewSpec.swift

[TESTS] Increase our code coverage in a few classes

---

Rocket.Chat/Managers/DraftMessageManager.swift
Rocket.ChatTests/Managers/DraftMessageManagerSpec.swift

[TESTS] Include missing tests on DraftMessagesManager

---

README.md

[DOCS] Add Swift Version & Licence badges to README

---

Gemfile
Rocket.Chat/Info.plist
Rocket.ChatTests/API/Requests/Message/PostMessageRequestSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift
Scripts/test-10.3-ipad.sh
Scripts/test-10.3-iphone.sh
Scripts/test-11.0-ipad.sh
Scripts/test-11.0-iphone.sh
Scripts/test.sh
Scripts/update_dependencies.sh
circle.yml

[CI] Update CircleCI file to use version 2

---

Rocket.Chat/Info.plist
Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
Rocket.ChatTests/Views/Chat/ChatTitleViewModelSpec.swift

[FIX] Bug on ChatTitleView after a few changes

---

circle.yml

[CI] Use CircleCI workflow correctly

---

Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib

[IMPROVEMENT] Remove text selection on the cell

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift

Bug only on TestFlight
Closes #1006

[HOTFIX] Duplicated date marks appearing

---

Rocket.Chat/Info.plist

[CHORE] Revert version number to 1.7.3 in order to release it

---

Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/DownloadManager.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

[FIX] Only invalidate user if user is authenticated in currently socket session

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Helpers/ChatCollectionViewFlowLayout.swift
Rocket.ChatTests/Helpers/ChatCollectionViewFlowLayoutSpec.swift

[FIX] Weird scrolling when loading new messages

---

codecov.yml

[CI] Try another thing with codecov so we dont fail PRs

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Possible crash in chat

---

Rocket.Chat/Storyboards/Chat.storyboard

[IMPROVEMENT] Make Info screen modal on iPad

---

Rocket.Chat/Info.plist

[RELEASE] Increment version to 1.7.4

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Items counter may change later in the code (different thread)

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Helpers/VoiceOver/VOLocalized.swift
Rocket.Chat/Helpers/VoiceOver/VOTextField.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Subscriptions/SubscriptionUserView.swift
Rocket.Chat/cs.lproj/VoiceOver.strings
Rocket.Chat/de.lproj/VoiceOver.strings
Rocket.Chat/en.lproj/VoiceOver.strings
Rocket.Chat/fr.lproj/VoiceOver.strings
Rocket.Chat/pl.lproj/VoiceOver.strings
Rocket.Chat/pt-BR.lproj/VoiceOver.strings

[NEW] Some VoiceOver improvements

---

Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Subscriptions/SubscriptionUserView.swift
Rocket.Chat/cs.lproj/VoiceOver.strings
Rocket.Chat/de.lproj/VoiceOver.strings
Rocket.Chat/en.lproj/VoiceOver.strings
Rocket.Chat/fr.lproj/VoiceOver.strings
Rocket.Chat/pl.lproj/VoiceOver.strings
Rocket.Chat/pt-BR.lproj/VoiceOver.strings

Message cells are now read as a whole.
Implements part of #968

[NEW] Improve VoiceOver for messages

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Info.plist

[CHORE] Bump app version to 1.8.0 (127)

---

Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.swift
Rocket.Chat/Views/Cells/Chat/AutocompleteCell.xib

[FIX] Autocompletion icon to each kind of cell: channels, mentions & commands

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Managers/Model/AuthSettingsManager.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

[HOTFIX] Random crashes on calling Realm in background

---

Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

We were subscribing before we had a connection. (Another bug squashed from our optimization :))

[FIX] Messages not updating after opening app or changing servers

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Requests/Subscription/SubscriptionMembersRequest.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message.swift
Rocket.Chat/Models/MessageReaction.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
Rocket.Chat/Views/Reactions/ReactionListView.swift
Rocket.Chat/Views/Reactions/ReactionListView.xib
Rocket.Chat/Views/Reactions/ReactionView.swift
Rocket.Chat/Views/Reactions/ReactionView.xib
Rocket.Chat/cs.lproj/VoiceOver.strings
Rocket.Chat/de.lproj/VoiceOver.strings
Rocket.Chat/en.lproj/VoiceOver.strings
Rocket.Chat/fr.lproj/VoiceOver.strings
Rocket.Chat/pl.lproj/VoiceOver.strings
Rocket.Chat/pt-BR.lproj/VoiceOver.strings
Rocket.ChatTests/Models/MessageReactionSpec.swift

|Preview|
|-|
|![](https://i.imgur.com/HiMepMn.png)|
|Progress|100%|
|-|-|
|View existing reactions|✅|
|Send existing reaction|✅|
|Remove reaction|✅|
|Send new reaction|Postponed|
||
|VoiceOver Support|✅|
|Test Coverage|✅|
Closes #689

[NEW] Add support for reactions

---

Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Reactions/ReactionListView.swift
Rocket.Chat/Views/Reactions/ReactionListView.xib

[WIP][NEW] Emoji picker to add new reactions

---

Rocket.Chat/Helpers/UploadHelper.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.ChatTests/Helpers/UploadHelperSpec.swift

[FIX] Remove size information when uploading a file (to prevent mistakes)

---

Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift

[FIX] Issue on connecting to old servers or trying to close connect screen

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[FIX] Layout issue on userView for iPhone X

---

Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Managers/Model/MessageManager.swift

[FIX] Message staying gray after sending with success via REST

---

Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Info.plist

[FIX] Fixed unit tests & increment app version

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Views/EmojiPicker/de.lproj/EmojiPicker.strings
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[i18n] Localize reaction feature to german

---

Rocket.Chat/de.lproj/Localizable.strings

[i18n] German localisation update

---

Rocket.Chat/Controllers/Chat/ChatControllerHeaderStatus.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[NEW] Show loading messages banner

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/External/Emojione/Emoji.swift
Rocket.Chat/External/Emojione/Emojione.swift
Rocket.Chat/Managers/Model/CustomEmojiManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Models/CustomEmoji.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/EmojiPicker/EmojiPicker.swift
Rocket.Chat/Views/EmojiPicker/EmojiPickerController.swift
Rocket.Chat/Views/EmojiPicker/EmojiView.swift
Rocket.Chat/Views/EmojiPicker/EmojiView.xib
Rocket.Chat/Views/EmojiPicker/cs.lproj/EmojiPicker.strings
Rocket.Chat/Views/EmojiPicker/de.lproj/EmojiPicker.strings
Rocket.Chat/Views/EmojiPicker/en.lproj/EmojiPicker.strings
Rocket.Chat/Views/EmojiPicker/fr.lproj/EmojiPicker.strings
Rocket.Chat/Views/EmojiPicker/pl.lproj/EmojiPicker.strings
Rocket.Chat/Views/EmojiPicker/pt-BR.lproj/EmojiPicker.strings
Rocket.Chat/Views/Reactions/ReactionView.swift
Rocket.Chat/Views/Reactions/ReactionView.xib
Rocket.ChatTests/Models/CustomEmojiSpec.swift

Preview:
https://imgur.com/a/zwjYM
Closes #699

[NEW] Add support for custom emojis in reactions

---

Rocket.Chat/Managers/Model/MessageManager.swift

[FIX] Fixed missing of messages when the app starts

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/WebViewEmbedded/WebViewControllerEmbedded.swift
Rocket.Chat/Extensions/URLExtension.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Managers/ServerManager.swift
Rocket.ChatTests/Extensions/URLExtensionSpec.swift

[FIX] Remove duplicated slashes from any URL that opens embedded in a WebView

---

README.md

[DOCS] Remove alpha reference from README

---

HISTORY.md

[DOCS] Remove HISTORY file since it's not being used

---

Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift

[FIX] Check for HTTP/HTTPS before encoding image URL

---

Rocket.Chat/Models/Subscription.swift

[FIX] Crash on toggling Favorite button

---

Rocket.Chat/Extensions/RealmExtension.swift

[FIX] Fix data getting mixed between servers

---

Rocket.Chat/de.lproj/Localizable.strings

[I18N] Small change for better language style [DE]

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift

[FIX] Spotlight not working

---

Rocket.Chat/Models/Subscription.swift

[FIX] Rare crash when entering room

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift

[FIX] Sometimes subscriptions going out of sync

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Extensions/StringExtensions.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings

[NEW] Forgot password

---

Rocket.Chat/API/Requests/Subscription/SubscriptionCreateRequest.swift
Rocket.Chat/NewRoomViewController.swift
Rocket.ChatTests/API/Requests/Subscription/SubscriptionCreateRequestSpec.swift

[FIX] Channels with special chars

---

Rocket.Chat/NewRoomViewController.swift

[FIX] Add members when creating a channel

---

Rocket.Chat/Helpers/UploadHelper.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.ChatTests/Helpers/UploadHelperSpec.swift

Reverts RocketChat/Rocket.Chat.iOS#1091

Revert "[FIX] Remove size information when uploading a file (to prevent mistakes)"

---

Rocket.Chat/API/Clients/InfoClient.swift
Rocket.Chat/Extensions/RealmExtension.swift

Let's see if this fixes it.
Closes #1149

[FIX] Sometimes app crashes after authentication

---

Podfile
Podfile.lock
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.ChatTests/API/Requests/Message/DeleteMessageRequestSpec.swift

[UPDATE] Update Starscream to 3.0.4

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/OAuthViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/OAuthManager.swift

[FIX] Loading fixed state after tapping any OAuth and tapping back

---

Rocket.Chat/API/API.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Managers/PushManager.swift
Rocket.Chat/Managers/Requests/InfoRequestHandler.swift
Rocket.Chat/NewRoomViewController.swift

Closes #1189 
I also added a TODO to handle errors in all REST requests, this is important in most of the cases.

[FIX] Alert on invalid URLs on Connect screen

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift
Rocket.Chat/Views/Sections/SubscriptionSectionView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift

Greatly reduced usage of imageWithTint. Especially in the places it was causing hangs.
Closes #1177

[FIX] App hangs once in a while

---

Rocket.Chat/Managers/Model/SubscriptionManager.swift

[HOTFIX] Crash when fetching subscriptions

---

Rocket.Chat/pl.lproj/Localizable.strings

[i18n] Localize missing polish strings

---

CONTRIBUTING.md
README.md
Rocket.Chat/API/Clients/UploadClient.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.Chat/cs.lproj/Localizable.strings
Rocket.Chat/de.lproj/Localizable.strings
Rocket.Chat/en.lproj/Localizable.strings
Rocket.Chat/fr.lproj/Localizable.strings
Rocket.Chat/pl.lproj/Localizable.strings
Rocket.Chat/pt-BR.lproj/Localizable.strings
circle.yml

Adds a dialog with two textfields to set filename (title) and adding a description (only visible on desktop without #1216).
Not the prettiest solution but at least adding a missing feature.

[NEW] Dialog to alter upload title and add description

---

Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/pl.lproj/EmojiPicker.strings

[i18n] Localize polish EmojiPicker strings

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
Rocket.Chat/External/RCEmojiKit/Views/EmojiView.xib
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthManager.swift

[CHORE] Fixed some code warnings & increment build version

---

Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Managers/AppManager.swift

[NEW] Open DM when selecting user in Members List

---

Rocket.Chat/Base.lproj/LaunchScreen.storyboard

LaunchScreen image was too big on iPad

[HOTFIX] Decrease maximum size of LaunchScreen image

---

Rocket.Chat/API/Requests/Command/RunCommandRequest.swift

[CHORE] Small typo on the file header comments

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/SAMLViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Models/LoginService.swift
Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift

Closes #461 
Let's test on some servers before merging.

[NEW] Support SAML authentication

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Models/Permission.swift

[NEW] Support post-readonly permission

---

Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/AuthManager.swift
Rocket.Chat/Models/Auth.swift

[FIX] Placeholder labels appearing when changing servers

---

Rocket.Chat/Managers/OAuthManager.swift
Rocket.Chat/Models/LoginService.swift
Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift

[FIX] Custom OAuth not working in some servers

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Managers/UserReviewManager.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

[IMPROVEMENT] Prompt "App Store rating" after reacting to a message

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Return key sending new message when editing

---

Rocket.Chat/Info.plist

[CHORE] Increment version to 2.0.1

---

Scripts/install_swiftlint.sh
Scripts/test-11.0-iphone.sh
Scripts/test-clean.sh
Scripts/test-coverage.sh
Scripts/test.sh
Scripts/update_dependencies.sh
circle.yml

[CI] Speed up tests

---

Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift

[FIX] Crash when displaying messages with duplicate custom emojis

---

Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift

[IMPROVEMENT] Make spotlight case insensitive

---

Rocket.Chat/Controllers/Auth/SignupViewController.swift

Some race condition problem
Closes #1284

[FIX] Not moving from register screen after registration

---

Rocket.Chat/Info.plist

[CHORE] Increment version to 2.0.2

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift

[TESTS] Add SubscriptionExtensionsSpec

---

Rocket.Chat/SettingsNavigationController.swift

[FIX] Call super on viewDidLoad to load all tintColor settings

---

Podfile.lock

[CHORE] Update most of our Pods

---

Rocket.Chat/Resources/fr.lproj/Localizable.strings

[I18N] Improve French translation

---

Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift

[IMPROVEMENT] Make users searching in create new room (inviting user) case and diacritic insensitive

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/External/RCEmojiKit/el.lproj/RCEmojiKit.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/VoiceOver.strings

Closes #1350 
Added Greek support in RCEmojiKit.strings, Localizable.strings, VoiceOver.strings Greek files.
BR,
Konstantinos

[I18N] Add Greek Localization

---

Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.xib
Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

|Preview|
|-|
|![](https://i.imgur.com/onDOcbS.png)|
Closes #1231 
I sent some test messages with fields at: https://open.rocket.chat/channel/cardoso_test

[NEW] Add support for attachment fields + some visual improvements

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[IMPROVEMENT] Navigate to the chat when tapping on already selected room

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/External/RCEmojiKit/es.lproj/RCEmojiKit.strings
Rocket.Chat/Info.plist
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/VoiceOver.strings

This file is going to be translated in another PR.

[I18N] Add Spanish language

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[IMPROVEMENT] When app reconnects, it should keep the scrolling position

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[HOTFIX] Avoid duplicating unread separator when reconnecting

---

Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

[HOTFIX] Disable collapse and fix height of file attachment view

---

Rocket.Chat/Resources/el.lproj/Localizable.strings

This is the update of greek strings that failed before. 
I created a fix/kmav-greek-localisation branch from the related commit.
Only the greek Localisation.strings is different.

[I18N] Update greek localization for new text

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Storyboards/Auth.storyboard

Resolves and closes issue #1363
Also it bypasses and closes PR #1364

[NEW] Add authViewController localization

---

Rocket.Chat/Resources/es.lproj/Localizable.strings

[I18N] Spanish strings

---

Rocket.Chat/Resources/es.lproj/VoiceOver.strings

[I18N] Update VoiceOver.strings spanish

---

Rocket.Chat/API/Requests/Message/UploadRequest.swift

[FIX] Typo on mimetype information when uploading a file

---

Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/VoiceOver.strings

Can translate strings from #1368 and #1379 here as well, just let me know once they are merged.

[I18N] Translate missing polish strings

---

Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
Rocket.ChatTests/Models/AttachmentSpec.swift

[BUG] App does not render preview picture for videos directly 

---

Rocket.Chat/Models/Attachment.swift
Rocket.ChatTests/Models/AttachmentSpec.swift
Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift

[IMPROVEMENT] Add a better support to fullpath URL attachments

---

Rocket.Chat/Storyboards/Auth.storyboard

[FIX] Terms of service and Privacy policy button spacing fixed

---

Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Storyboards/Auth.storyboard

[FIX] Make some adjustments on the connect screen & improve pt-BR translation

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.ChatTests/Settings/EditProfileViewModelSpec.swift
Rocket.ChatTests/Settings/NewPasswordViewModelSpec.swift

Add more tests to Profile feature

[IMPROVEMENT] Add more tests to Profile feature

---

Rocket.Chat/API/APIRequest.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift

[FIX] Invalid url path building

---

Rocket.Chat/Storyboards/Preferences.storyboard

[CHORE] Use BODY & change detail color into settings labels

---

Rocket.Chat/Controllers/Settings/PreferencesViewController.swift

[FIX] FLEX cell in Preferences wasn't being selected

---

Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift

[NEW] Support "Edit Profile" settings

---

Rocket.Chat/Info.plist

[RELEASE] Increment build version to 2.1.0 (150)

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
Rocket.Chat/Managers/WindowManager.swift
Rocket.Chat/Storyboards/Preferences.storyboard
Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift
Rocket.ChatTests/Controllers/EditProfileTableViewControllerSpec.swift

[IMPROVEMENT] Profile auth settings tests

---

Podfile
Podfile.lock
Rocket.Chat/Managers/Socket/SocketManager.swift

[CHORE] Revert back Starscream to 2.1.1 to prevent loosing connection on WebSocket

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift

[NEW] Placeholder on authentication fields via Settings

---

Rocket.Chat/Info.plist

[CHORE] Increment build number

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Models/Email.swift
Rocket.Chat/Models/Mapping/UserModelMapping.swift

[BUG] Persist user e-mail to realm

---

Rocket.Chat/Managers/Model/AuthManager.swift

[FIX] Not persisting server version

---

Rocket.Chat/Info.plist

[CHORE] Increment version of the app to 2.1.1 (152)

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/API/Requests/Message/ReactMessageRequest.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
Rocket.ChatTests/API/Requests/Message/ReactMessageRequestSpec.swift

[IMPROVEMENT] Migrate reaction request to REST API

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.ChatTests/API/Clients/CommandsClientSpec.swift
Rocket.ChatTests/API/Clients/InfoClientSpec.swift
Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift

Updated a few libraries:
- Crashlytics
- Fabric
- Instabug (and moved to only Debug & Beta)
- semver (and changed to use the default repo)
- SDWebImage

[CHORE] Update CocoaPods to 1.5.0 & a few of the Pods

---

PLANNING.md

[DOCS] Creates a initial version of our planning document

---

PLANNING.md

[DOCS] Fixed some works in our planning document

---

Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
circle.yml

- Added the previously removed devices, running on iOS 10.
- Added a test for the iPhone X.
- Resolved conflicts in `MessagesClientSpec`

[CI] Added the previously removed iOS 10 devices for Circle CI

---

CONTRIBUTING.md

[DOCS] CONTRIBUTING.md updated to say Swift 4.1

---

Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift

[FIX] Edit Profile stuck when saving without changes

---

Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Managers/MarkdownManager.swift
Rocket.ChatTests/MarkdownManagerSpec.swift

[FIX] Rare crash when parsing markdown links

---

Rocket.Chat.ShareExtension/Info.plist

[IMPROVEMENT] Share extension: support 2 attachment combos

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/DatabaseManager.swift
Rocket.Chat/Managers/PushManager.swift
Rocket.ChatTests/Managers/AppManagerSpec.swift
Rocket.ChatTests/Managers/DatabaseManagerSpec.swift
Rocket.ChatTests/Managers/PushManagerSpec.swift

Looks like we had a regression after we started supporting paths 🤔

[FIX] Not opening corresponding room after pressing notification

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/AppDelegate.swift
Rocket.Chat/Rocket.Chat.entitlements

[NEW] Add support to Universal Links (go.rocket.chat)

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Info.plist

[CHORE] Update version of the app to new Beta release

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Rocket.Chat/Managers/Socket/Response/SocketError.swift

[FIX] False positives on invalid session

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[CHORE] Remove + from the name, increment version & fix Instabug for Release builds

---

README.md

[DOCS] Updated README.md to say Swift 4.1

---

Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift

[FIX] Some messages are missing when loading history

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/MainChatViewController.swift

[IMPROVEMENT] Clear chat when logging out

---

Rocket.Chat/Managers/Model/AuthSettingsManager.swift
Rocket.Chat/Models/Attachment.swift
Rocket.Chat/Models/AuthSettings.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
Rocket.Chat/Models/Mapping/ChannelModelMapping.swift
Rocket.Chat/Models/Mapping/MentionModelMapping.swift
Rocket.Chat/Models/Mapping/MessageURLModelMapping.swift
Rocket.Chat/Models/Message/Channel.swift
Rocket.Chat/Models/Message/Mention.swift
Rocket.Chat/Models/Message/MessageReaction.swift
Rocket.Chat/Models/Message/MessageURL.swift
Rocket.ChatTests/Managers/AuthSettingsManagerSpec.swift
Rocket.ChatTests/Models/ChannelSpec.swift
Rocket.ChatTests/Models/MentionSpec.swift
Rocket.ChatTests/Models/MessageReactionSpec.swift
Rocket.ChatTests/Models/MessageURLSpec.swift

[IMPROVEMENT] Investigate and update models that unnecessarily inherit from BaseModel

---

Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[FIX] Sync localization files

---

Rocket.Chat/API/API.swift
Rocket.Chat/API/APIError.swift
Rocket.Chat/Managers/Requests/InfoRequestHandler.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[IMPROVEMENT] Improve the message of SSL invalid when connecting to the server

---

Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[I18N] Remove the "Message" string from actions

---

Rocket.Chat/Managers/Model/AuthSettingsManager.swift

[CRASH] Crash on clearing AuthSettings objects

---

Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift

[HOTFIX] Login services not mapping correctly

---

Rocket.Chat.ShareExtension/Base/SENavigationController.swift
Rocket.Chat.ShareExtension/Info.plist

[FIX] Share extension not working with Notes and App Store

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Info.plist

[CHORE] Update app & build version to 2.3.0

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift

[IMPROVEMENT] Logic of signup button hiding & some code adjustments

---

Rocket.Chat/Storyboards/Chat.storyboard

[FIX] Search messages bug on iPhone X

---

Rocket.Chat/Managers/Model/CustomEmojiManager.swift
Rocket.Chat/Models/CustomEmoji.swift

I didn't notice any noticeable performance changes from this caching mechanism. If i'm wrong, please correct me. 
Otherwise LGTM.

[FIX] Custom emojis not updating when changing servers

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Increment version to release 2.3.0

---

Rocket.Chat/Views/Chat/RCTextView.swift

[FIX] Crash on UITextView related to handling URLs

---

Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift

[FIX] Check on EmojiPicker for invalid IndexPath

---

Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Models/Message/Message.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[FIX] Message pinned not rendering correctly

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/InfoClient.swift
Rocket.Chat/API/Requests/General/PermissionsRequest.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.ChatTests/API/Clients/InfoClientSpec.swift
Rocket.ChatTests/API/Requests/General/PermissionsRequestSpec.swift

[IMPROVEMENT] Migrate "get permissions" API request to HTTP

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/API/Requests/Subscription/SubscriptionReadRequest.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.ChatTests/API/Requests/Subscription/SubscriptionReadRequestSpec.swift

[IMPROVEMENT] Migrate request that marks subscription as read to HTTP 

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Managers/Model/MessageManager.swift

[FIX] Infinite loader on the top for very small conversations (without scrolling)

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Unread reset logic

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Unread separator

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/AuthClient.swift
Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/API/Requests/Authentication/LoginRequest.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
Rocket.Chat/Controllers/Auth/TwoFactorAuthenticationViewController.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.ChatTests/API/Requests/Authentication/LoginRequestSpec.swift

[IMPROVEMENT] Migrate login network request to HTTP

---

Podfile.lock

[CHORE] Update Realm and SwiftyJSON

---

Rocket.Chat/Controllers/Notification/NotificationViewController.swift
Rocket.Chat/Controllers/Notification/NotificationViewController.xib

Notification font size changed to 15 points to better match the rest of the app.

[IMPROVEMENT] Notification font size changed

---

Rocket.Chat/API/APIError.swift

[FIX] Infinite recursion on APIError description

---

Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift

[FIX] Accessing UI from background thread

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Models/File.swift
Rocket.ChatTests/Models/DrawingBrushColorSpec.swift
Rocket.ChatTests/Models/DrawingViewModelSpec.swift
Rocket.ChatTests/Models/FileSpec.swift

[IMPROVEMENT] Change type we check for video/audio/images on the mimetype of File objects

---

Podfile.lock

[CHORE] Update CocoaPods to 1.5.2 and few libraries (Instabug & SwiftLint)

---

Rocket.Chat/API/Requests/User/UpdateUserRequest.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift

[FIX] Choose username not working with REST API authentication

---

Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift

[FIX] Do not make dumb updates on Subscription mapping & update subscription object mapping on request results

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/API/API.swift
Rocket.Chat/API/Clients/CommandsClient.swift
Rocket.Chat/API/Clients/InfoClient.swift
Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/SignupViewController.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
Rocket.Chat/Controllers/Preferences/Profile/NewPasswordTableViewController.swift
Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/Model/AuthSettingsManager.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
Rocket.Chat/Models/Message/Message.swift
Rocket.Chat/Models/Message/MessageReply.swift
Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift

- Changed the default thread of completion block on REST to the main thread;
- Subscription object is now optional on the Message, because sometimes we don't persist it (search, pinned, starred lists...);
- Fixed crashes on handling errors on authentication after the changes on REST;

[FIX] Crashes on Authentication, subscription optional in Message & more

---

Rocket.Chat/API/API.swift
Rocket.Chat/API/Clients/InfoClient.swift
Rocket.Chat/API/Requests/User/UpdateUserRequest.swift
Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
Rocket.Chat/Controllers/Auth/SignupViewController.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift

There was a problem with the updateOwnBasicInfo API. If we send more than username it returns an error.
Also we had this code:
```swift
DispatchQueue.main.asyncAfter(deadline: .now() + 1)
```
Looks like it was waiting for the 'user' object to arrive in the socket. So I replaced it with a /me request.

[FIX] Sign up flow not completing

---

Rocket.Chat/Managers/NotificationManager.swift

Addresses one of the concerns raised in #1563

[IMPROVEMENT] Removed markdown from in-app notifications

---

Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Rocket.Chat/Models/User/UserQueries.swift
Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift

[FIX] Infinite requesting API and empty userId for myself DMs

---

Rocket.Chat/Controllers/Auth/AuthViewController.swift
Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
Rocket.Chat/Managers/OAuthManager.swift

Also fixes a problem with ports not going into the redirect url

[FIX] API_Gitlab_Url setting not taking actual effect

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/API/Requests/Room/RoomsRequest.swift
Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
Rocket.Chat/Info.plist
Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Rocket.ChatTests/API/Requests/Room/RoomsRequestSpec.swift
Rocket.ChatTests/API/Requests/Subscription/SubscriptionsRequestSpec.swift

[FIX] Call completion block even on failures & errors

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift

[FIX] Cell was not updating for reactors

---

Rocket.Chat/Resources/ru.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/VoiceOver.strings

I prepared a translation into Russian for the iOS version.

[NEW] Russian translation file

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Subscriptions/ServersListView.swift

- Fixes the weird scrolling behavior for `SubscriptionsViewController`
- Corrects the layout for Safe area insets
- Fix select server button arrow not reverting to its default state when the same server is selected.

[FIX] Fix weird scrolling behavior on Subscriptions VC

---

Rocket.Chat.xcodeproj/project.pbxproj

[FIX] Project adjustments to support Russian language properly

---

Rocket.Chat/Resources/ru.lproj/Localizable.strings

The translation of some items has been clarified.

[FIX] Update RU Localizable.strings

---

Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
Rocket.ChatTests/Controllers/NotificationViewControllerSpec.swift
Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift

[FIX] Tests fixed

---

Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
Rocket.Chat/Controllers/Preferences/Profile/StatusViewModel.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings
Rocket.Chat/Storyboards/Preferences.storyboard
Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift

[NEW] Add Administration and Logout to Preferences screen

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[FIX] Close serversView and sortingView on SubscriptionsVC when search bar is tapped

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

[IMPROVEMENTS] Subscriptions & Rooms request improvements & bug fixes

---

Rocket.Chat/Resources/ru.lproj/Localizable.strings

[IMPROVEMENT] Improvements in Russian translation

---

Rocket.Chat/Controllers/Auth/LoginTableViewController.swift

[BUG][NEW ONBOARDING] Cannot login using 2FA on

---

Podfile
Podfile.lock
Rocket.Chat.xcodeproj/project.pbxproj

[FIX] Not being able to close images or videos in iPhone X

---

Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.ChatTests/Managers/ServerManagerSpec.swift

[IMPROVEMENT][NEW ONBOARDING] Update en strings according to suggestions

---

Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.xib
Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.xib
Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.xib
Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.xib
Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.xib

[IMPROVEMENT] Some UI adjustments for iPad

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[BUG] Resolve issue on breaking the cell layout for new messages on loading history

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift

[IMPROVEMENT] Resolve strong retain cycle on SubscriptionViewController

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewController.swift
Rocket.Chat/Controllers/Subscriptions/AudioFileViewController.swift
Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Theme/Theme.swift
Rocket.Chat/Theme/ThemeableViews.swift
Rocket.Chat/Views/Loader/LoaderView.swift
Rocket.Chat/Views/Subscriptions/ServersListView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingSeparatorView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift

This PR also includes some minor improvements.

[IMPROVEMENT][THEME] Use the new colors for the dark theme

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

[BUG] Sometimes set username screen appears when opening the app when username is already set

---

Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings

Added missing Greek translations. Also did a single ament in English translation of 
`"servers.action.disconnect.alert.message" = "Do you want to disconnect from \"%@\" server?";
`

[I18N] Added Greek translations

---

Rocket.Chat/API/API.swift
Rocket.Chat/API/Middlewares/VersionMiddleware.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Extensions/API/APIExtensions.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.Chat/Views/Base/BaseNavigationBar.swift
Rocket.Chat/Views/Subscriptions/ServersListView.swift
Rocket.Chat/Views/Subscriptions/ServersListViewModel.swift

We are getting rid of all these memory leaks with this PR:
Closes #1801
Closes #1815 
Closes #1812

[IMPROVEMENT] Fix some memory related issues

---

Rocket.Chat/API/Clients/AuthClient.swift
Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/API/Requests/Room/RoomsRequest.swift
Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerRecover.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Rocket.Chat/Models/Auth/Auth.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift

- Add the updatedAt filter to rooms & subscriptions now, fixed a bug that was happening before related to having only one field saving the date;
- Adjusted the `width` of the view related to the text so we don't calculate wrongly;

[CHORE] Couple improvements on the API requests & UI

---

Rocket.Chat/Resources/pl.lproj/Localizable.strings

[i18n] Add polish translation for new strings

---

Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

[CRASH] Our users are experiencing random crashes when logging out

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings
Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.swift

- Fix subscriptions title view servers button not getting themed properly on iOS 10 
- Synchronize Russian translations
- The logout confirmation text has been corrected to "Yes, logout", from "Yes, logout me".
- Fix cancel button not getting hidden when the preferences are opened while editing the search bar text (iOS 10)

[FIX] Subscriptions title view servers button not getting themed properly on iOS 10 and synchronize Russian translations

---

Rocket.Chat/API/Clients/AuthClient.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift

[IMPROVEMENT] Fallback to websocket when registering username and fix a bug related to websocket authentication

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

Not sure when this broke, but here's the fix.

[FIX] Emoji avatars disappearing after a second

---

Rocket.Chat.ShareExtension/Resources/pt-PT.lproj/Localizable.strings

Not sure if it's needed but i suppose so.
So, here it is.

Portuguese (PT) translation

---

Rocket.Chat/Controllers/Auth/WelcomeViewController.swift

[BUG] App crashes upon clicking +Create a new workspace

---

Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Rocket.ChatTests/Managers/Launcher/BugTrackingCoordinatorSpec.swift
Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift

[FIX] Tests

---

Podfile
Podfile.lock
Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
Rocket.Chat/Managers/ImageManager.swift
Rocket.Chat/Views/Avatar/AvatarView.swift

[BUG] Profile picture didn't change

---

Rocket.Chat/Views/Chat/RCTextView.swift

[BUG] Channel deep links not working

---

Rocket.Chat/Controllers/Auth/AuthNavigationController.swift

[FIX] Rotation related issues on onboarding flow

---

Rocket.Chat/Theme/ThemeableViews.swift

[FIX] Table view cells getting incorrectly themed

---

Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Rocket.Chat/Storyboards/Auth.storyboard

[IMPROVEMENT] Login Page > "Create an Account" should stay in place when the keyboard is hidden

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Resources/Assets.xcassets/Icons/Icon Filter.imageset/Contents.json
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Subscriptions/ServersListView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.xib

This region should be tappable now.

[IMPROVEMENT] Tappable subscriptions sorting view

---

Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift

[FIX] Incorrectly sorting when "UI_Use_Real_Name" is activated

---

Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

[BUG] Subscriptions list is empy when first joining a server

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Text input bar not moving to the bottom of the screen.

---

Rocket.Chat/Managers/AppManager.swift

[BUG] Chat page > Three-Dot menu > Members > Members modal stays open after selecting Message

---

Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings

[IMPROVEMENT] Join the Community > Create new account > Register button keeps loading when registering with null password

---

Rocket.Chat/Views/Subscriptions/ServersListView.swift

[BUG] Letting the user logout from all servers on server list

---

Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Managers/AnalyticsManager.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManager.swift

[IMPROVEMENT] Improve message sent events and add some user properties

---

Rocket.Chat/Storyboards/Subscriptions.storyboard

[BUG] Adjust unread margins for iPads on missing Outlets connections

---

Rocket.Chat/Resources/fr.lproj/Localizable.strings

All TODOs, a few typos, grammatical issues and clarity issues taken care of.
Checks "fr" in #1830

[I18N] Updated French Localization for 3.0.0

---

Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
Rocket.Chat/Views/Form/Cells/TextFieldTableViewCell.swift
Rocket.Chat/Views/Form/FormTableViewCell.swift

[IMPROVEMENT] Restrict Channel name to a certain number of characters

---

Rocket.Chat.ShareExtension/Resources/fr.lproj/Localizable.strings

Completely forgot I had to translate the Share Extension too...
Should have been submitted in #1918.
Checks "fr" in #1830 (for good this time)

[I18N] Updated French Localization for 3.0.0 Share Extension

---

Rocket.Chat/Views/Chat/RCTextView.swift

 [CRASH] Crashing when trying to open an URL from UITextView

---

Rocket.Chat/Models/LoginService.swift

[FIX] Custom OAuth not working if Authorize Path is full URL

---

Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCellCondensed.swift

[IMPROVEMENT] Theming performance improvement in SubscriptionCell

---

Rocket.Chat/API/Clients/CommandsClient.swift
Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/Extensions/Models/UserExtensions.swift
Rocket.ChatTests/API/Clients/CommandsClientSpec.swift

This PR improves the performance of the app after connecting moving all the Command database procedures to the correct thread execution, it also mark the rooms as read manually in DB and update the last message object to give the user a better impression on very slow internet connections.

[CHORE] Performance improvements & couple of improvements

---

Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift

[FIX] Attachment coloring does not work

---

Rocket.Chat/Theme/ThemeableViews.swift
Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.swift
Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.xib

Closes #1912 
Closes #1913 
Closes #1931

[FIX] Minor theming issues

---

Rocket.Chat/Controllers/Base/BaseNavigationController.swift
Rocket.Chat/Controllers/Base/BaseViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift

[FIX] Navigation Bar transparent after going to DM via User Detail

---

Rocket.Chat/Controllers/Notification/NotificationViewController.swift
Rocket.Chat/Controllers/Notification/NotificationViewController.xib
Rocket.Chat/Views/Notification/NotificationView.swift

This PR introduces some improvements to the in-app notifications
- Support multiple lines of text message (upto 3 lines)
- Background changed from a blur effect to a solid color

[IMPROVEMENT] In app notification now support multiple lines of text

---

Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json
Rocket.Chat/Theme/Theme.swift
Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.swift
Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.xib
Rocket.Chat/Views/Subscriptions/ServersListView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift

[IMPROVEMENT] Theme upload banner

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[NEW] Add 3D Touch interaction to the Subscriptions List

---

Rocket.Chat/Controllers/Auth/AuthTableViewControllerLoginServices.swift
Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift

[FIX] Crash when trying to share a room on an iPad

---

Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Star-Filled.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Star.imageset/Contents.json

[FIX] Star glyph now gets themed appropriately

---

Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
Rocket.ChatTests/Helpers/UploadHelperSpec.swift
Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
Rocket.ChatTests/Models/SubscriptionSpec.swift

This PR also fixes a crash on Realm related to deleted messages subscriptions.

[TESTS] Fixed all breaking tests and add a new one for hidden rooms

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift

[FIX] Race condition on first user, iOS 11 optimization on the list & update titleView for Subscription updates

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[FIX] App not refreshing messages when opening from notification or changing network status

---

Podfile.lock

[CHORE] Update some of the Pods

---

Rocket.Chat/Extensions/Models/UserExtensions.swift

[CRASH] Avoid getting the wrong thread on user status updates

---

Rocket.Chat/Resources/de.lproj/InfoPlist.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/VoiceOver.strings

Partially closes #1830
@soundstorm Feel free to review :)

[I18N] Updated German Localization for 3.0.0

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Rocket.Chat/Resources/de.lproj/InfoPlist.strings
Rocket.Chat/Resources/el.lproj/InfoPlist.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/InfoPlist.strings
Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCellCondensed.swift

Closes #1959 
Closes #1648 
Closes #1094

[CHORE] Badge updates & fixes, also keep the cell selected on iPads

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Theme/ThemeableViews.swift

[FIX] Theming on swipe actions

---

Rocket.Chat/Info.plist
Rocket.Chat/Resources/cs.lproj/InfoPlist.strings
Rocket.Chat/Resources/de.lproj/InfoPlist.strings
Rocket.Chat/Resources/el.lproj/InfoPlist.strings
Rocket.Chat/Resources/en.lproj/InfoPlist.strings
Rocket.Chat/Resources/es.lproj/InfoPlist.strings
Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
Rocket.Chat/Resources/pl.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
Rocket.Chat/Resources/ru.lproj/InfoPlist.strings

[i18n] Localize usage (permission) descriptions from Info.plist file

---

Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift

[FIX] Resolve sorting problem when fname property is empty and is sorting by it

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

There was a bug that when we started searching for a room and keyboard appeared, not all rows were visible because of keyboard being on top of the bottom part of tableView.

[FIX] Adjust subscriptions list according to keyboard's frame

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/WindowManager.swift

[BUG] Deeplink auth not working properly

---

Rocket.Chat.ShareExtension/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/InfoPlist.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings

@Sameesunkaria @rafaelks 
e-mail/email word cannot be translated in greek without creating a string of 20-30 characters :)
It is ok like that.

[I18N] Update greek translations for 3.0.0

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[FIX] Flickering tableview cells on iPad

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/WelcomeViewController.swift

[FIX] Use transparent navigationBar on the Onboarding screens

---

Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift

[BUG] Reduce the amount of time to ~28 hours instead of the same second

---

Rocket.Chat/API/Requests/Room/RoomsRequest.swift
Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift

[CHORE] Use ISO formatter & encode the string before sending it to the URL

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Managers/DatabaseManager.swift
Rocket.Chat/Managers/DatabaseManagerAuthSettings.swift

[FIX] Share extension missing reference compile error

---

Rocket.Chat/Managers/Socket/Response/SocketError.swift
Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Rocket.Chat/Managers/Socket/SocketManager.swift

[FIX] Invalid session support

---

Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift

[CRASH] Fatal Exception: NSInternalInconsistencyException -[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Increment app version to 3.0.1

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist

This pull-request fixes a bunch of crashes happening in ChatViewController related to deleted messages.

[CRASH] Subscription to deleted messages

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

This is more of putting a bandaid on the problem, rather than a fix. But it works fine. We'll have to wait for apple to actually address this issue.
Closes #1818

[HOTFIX] Search bar clear button not hiding

---

Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State black.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State dark.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State light.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/AttachFiles.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/ChooseFromLibrary.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/RecordVideo.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/TakeAPhoto.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Error.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json

Scales for pdf assets should be set to **Individual Scales**.

[ROUTINE] Set proper assets' scales for pdf images

---

Rocket.Chat/Controllers/Notification/NotificationViewController.xib

[IMPROVEMENT] Increase contrast for in-app notifications

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift

[FIX] Subscriptions should not repeat when they are grouped by type

---

Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift

[CRASH] Realm operating on the wrong thread on fallbacks for sendMessage & react

---

Rocket.Chat/API/Requests/General/SpotlightRequest.swift
Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift

[BUG] Search needs to take in consideration user's full name & room's fname property

---

Rocket.Chat/Managers/DatabaseManager.swift

[BUG] Sometimes the user keeps looping to connect into the server (Realm becomes inconsistent

---

Rocket.Chat/Resources/ru.lproj/InfoPlist.strings

[i18n] Improvements in Russian translation

---

Rocket.Chat/Controllers/Chat/ChatViewController.swift

[FIX] Owner user is not able to send message on a public readonly channel (issue #2003)

---

README.md

[CHORE] Update images to the new layout

---

README.md

Update images to the ones from App Store

---

CONTRIBUTING.md

Should use bundler to install dependencies

[DOCS] Update CONTRIBUTING.md

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Helpers/DeepLink.swift
Rocket.ChatTests/Helpers/DeepLinkSpec.swift

[IMPROVEMENT] Support https://go.rocket.chat/ deeplinks

---

README.md

[DOCS] Update screenshots

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[IMPROVEMENT] Don't hide Navigation Bar on Searching Rooms on iPad

---

Rocket.Chat.ShareExtension/Base/SENavigationController.swift
Rocket.Chat.ShareExtension/Extensions/SEStateAPI.swift
Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
Rocket.Chat.ShareExtension/Rooms/SERoomsViewModel.swift
Rocket.Chat.ShareExtension/State/ActionCreators/SelectServer.swift
Rocket.Chat.ShareExtension/State/ActionCreators/SubmitContent.swift
Rocket.Chat.ShareExtension/State/SESearchState.swift
Rocket.Chat.ShareExtension/State/SEState.swift
Rocket.Chat.ShareExtension/State/SEStore.swift
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift

Lots of things to improve here, code as well, I'll add them below as I finish them.
Closes #1874

[IMPROVEMENT] Improve Share Extension experience 

---

Rocket.Chat/Controllers/Base/MainSplitViewController.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[FIX] iPhone plus navigation weird on landscape

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Prepare app to release 3.0.3

---

Podfile.lock

[UPDATE] Update Realm, Nuke & Firebase from CocoaPods

---

Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings

[I18N] Update all pt-BR strings for the notifications screen

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Rocket.Chat/Info.plist

[HOTFIX] Deeplink auth for servers without login services

---

README.md

[DOCS] Update top header image & logo size

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Models/User/UserPermissions.swift

[RELEASE] Merge release 3.0.4 into MASTER

---

Rocket.Chat/Extensions/UIImageExtension.swift

[FIX] Handle uploading images when there is no file size limit

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[BUG] It is not possible to change server

---

Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Models/Subscription/Subscription.swift

[IMPROVEMENT] Update UI optimistically after editing message

---

Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift

[FIX] Messages getting cut and scrolling

---

Rocket.Chat/Resources/ja.lproj/InfoPlist.strings
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.Chat/Resources/ja.lproj/VoiceOver.strings

Add japanese translation file.

[NEW] Add Japanese translation file

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/External/RCEmojiKit/ja.lproj/RCEmojiKit.strings

[I18N] Add Japanese to the Project

---

Rocket.Chat/Resources/ja.lproj/Localizable.strings

Sameesunkaria requested update of the translated file.
For details, refer to the following URL.
https://github.com/RocketChat/Rocket.Chat.iOS/pull/2145

[I18N]Japanese translation file update

---

Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings

[I18N] Sync translations

---

Rocket.Chat/Controllers/Chat/ChatDataController.swift
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift

[FIX] Fixed a crash on invalidated object, Japanese translation file & missing strings

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift

[HOTFIX] Fix not showing room selection when using shortcut

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Managers/AnalyticsManager.swift
Rocket.Chat/Managers/PushManager.swift

Closes #2113
This PR adds a new event call to when user is replying a message via notification.

[CHORE] Add an event to when replying a notification

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Info.plist

[CRASH] Validate Subscription object before using it

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift

[HOTFIX] Incorrect index path on tapping a cell in subscriptions VC

---

Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings

[CHORE] Update subtitle on Welcome screen to "Team Communication"

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Models/Subscription/Subscription.swift
Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

[FIX] Crash on invalid subscription managed object

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Rocket.Chat/Managers/Model/MessageManager.swift
Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
Rocket.Chat/Managers/Model/MessageManager/MessageManagerSystemMessages.swift
Rocket.Chat/Managers/Socket/SocketManager.swift
Rocket.Chat/Models/Message/Message.swift
Rocket.ChatTests/Managers/MessageManagerSpec.swift
Rocket.ChatTests/Managers/MessageManagerSystemMessageSpec.swift

[NEW] Handle system/private messages stream

---

Podfile.lock
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Views/Chat/ChatTitleView.xib

[BUG + UPDATES] Update Realm & Firebase, fixed bug introduced on Community button and fixed a bug with long chats name

---

Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Managers/MarkdownManager.swift
Rocket.Chat/Managers/MessageTextCacheManager.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift

I have made a few architectural decisions to help with the performance, feel free to ask about anything related to the implementation.
Closes #2146

[IMPROVEMENT] Theme background for code blocks and markdown quotes

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Increment version of the app for a new release

---

Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
Rocket.Chat/Managers/AnalyticsManager.swift

[CHORE] Log the opening of the admin to understand the usage of it

---

README.md

[CHORE] Add TestFlight invitation link to the README

---

README.md
Rocket.Chat/API/Requests/Room/RoomMentionsRequest.swift
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
Rocket.Chat/Managers/AnalyticsManager.swift

[BUG] Fixed mentions list sorting

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/ChatItems/SequentialMessageChatItem.swift

[IMPROVEMENT] Sequential message

---

Podfile
Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/ChatViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
Rocket.Chat/Models/Message/UnmanagedMessage.swift
Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift

[IMPROVEMENTS] Bug fixes & improvements on the new composer & components

---

Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift

[BUG] Duplicated data on receiving modifications from Realm

---

Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib

[NEEDS THIS PR TO BE MERGED AND UPDATED TO BUILD PROPERLY](https://github.com/RocketChat/RocketChatViewController/pull/22)
- Fix an issue that was breaking the entire layout of basic message cells and sequential message cells
- Add support for safe areas for all the cells and their inner content (landspace on iPhone X, for example)
- Simplify and align the values of superview referenced constraints

[IMPROVEMENT] Cell sizing

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift

[NEW] Quote message headers

---

Rocket.Chat/API/Requests/General/PermissionsRequest.swift

[CHORE] Update API endpoint of Permissions list

---

Podfile
Podfile.lock
Pods/DifferenceKit/README.md
Pods/DifferenceKit/Sources/Algorithm.swift
Pods/DifferenceKit/Sources/AnyDifferentiable.swift
Pods/DifferenceKit/Sources/ArraySection.swift
Pods/DifferenceKit/Sources/Changeset.swift
Pods/DifferenceKit/Sources/ContentEquatable.swift
Pods/DifferenceKit/Sources/Differentiable.swift
Pods/DifferenceKit/Sources/ElementPath.swift
Pods/DifferenceKit/Sources/Extensions/UIKitExtension.swift
Pods/DifferenceKit/Sources/StagedChangeset.swift
Pods/Local Podspecs/RocketChatViewController.podspec.json
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Pods/Target Support Files/DifferenceKit-Core/Info.plist
Pods/Target Support Files/DifferenceKit/Info.plist
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift

[CHORE] Update DifferenceKit & improvements on the data controller, also fixes unit tests

---

Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Theme/ThemeableViews.swift

A big thanks to @Sameesunkaria for letting me know that these improvements were needed 👍

[CHORE] Refactor chat theme adoption

---

Rocket.Chat/Controllers/Chat/MessagesViewController.swift

[IMPROVEMENT] Reflect data changes on dataSorted and dataNormalized

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseTextAttachmentChatItem.swift
Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift

[FIX] Crash when tapping on collapsible quote

---

Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Rocket.ChatTests/Views/AvatarViewSpec.swift

[BUG] Missing data on the list & fixed unit tests

---

Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Pods/RocketChatViewController/RocketChatViewController/Classes/UIKitExtension.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift

[FIX] Recalculate sequential messages size when they were not sequential before an update

---

Rocket.Chat/Theme/ThemeableViews.swift

[FIX] Light keyboard showing in dark themes in composer

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift

[FIX] Add trailing space after autocompletion

---

Rocket.Chat/Controllers/Chat/MessagesViewModel.swift

[FIX] UI call being made on background thread to fetch current theme

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift

[CHORE] Remove identify/anonymize mechanisms from AnalyticsCoordinator

---

Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift

- Resolves race condition on accessing the data objects;
- Resolves freezing on video thumb generation;
- Make page size be always 30;

[FIX] Freezing video thumb generation & race condition on data 

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Views/Chat/New Chat/Cells/LoaderCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/LoaderCell.xib
Rocket.Chat/Views/Chat/New Chat/ChatItems/LoaderChatItem.swift

[NEW] Add support to "Loader Cell" on the top of the list

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerEditing.swift

[FIX] Open Keyboard when replying

---

Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift

[CHORE] Update our SDK version with spacing adjustments

---

Rocket.Chat/Models/Subscription/Subscription.swift
Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift

[BUG] Avatars for Subscription not using the `#` char on the URL

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Clients/MessagesClient.swift
Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
Rocket.Chat/Managers/MessageTextCacheManager.swift
Rocket.Chat/Models/Message/Message.swift
Rocket.Chat/Models/Message/UnmanagedMessage.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
Rocket.ChatTests/Models/SubscriptionLastMessageSpec.swift

[CHORE] Only use unmanaged objects on transforming markdown cache

---

Podfile.lock
Pods/Local Podspecs/RocketChatViewController.podspec.json
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/Composer/Assets/cs.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/de.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/el.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/en.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/es.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/fr.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/ja.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/pl.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/pt-BR.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/pt-PT.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Assets/ru.lproj/Localizable.strings
Pods/RocketChatViewController/Composer/Classes/Addons/Editing/EditingView.swift
Pods/RocketChatViewController/Composer/Classes/Library/ComposerLocalizable.swift
Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift

- Adds localization to composer
- Makes topHeight overridable

[CHORE] Update RocketChatViewController

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Extensions/StringExtensions.swift
Rocket.Chat/Models/Attachment/Attachment.swift
Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Models/Message/UnmanagedMessage.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift

[WIP][FIX] Collapsible cells & user initiated interaction flow generally

---

Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift

[FIX][RCVC] Inverted scrolling shortcuts

---

Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift

[FIX] Updates on Subscription weren't being reflect on the database

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift

[FIX][RCVC] Only return to send on iPad

---

Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib

btw read receipts have not to do with this issue
Closes #2338

[FIX] Long names with read receipt are breaking the date field

---

Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib

[FIX] Fixed quote attachment resizing

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift

[RELEASE] Merge release 3.1.2 into MASTER

---

Rocket.Chat/API/Clients/SubscriptionsClient.swift
Rocket.Chat/API/Requests/General/DirectoryRequest.swift
Rocket.Chat/API/Requests/Message/ReadReceiptsRequest.swift
Rocket.Chat/Controllers/Chat/AddUsersViewController.swift
Rocket.Chat/Controllers/Chat/MembersListViewController.swift
Rocket.Chat/Models/User/UnmanagedUser.swift
Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.swift
Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListViewController.swift

- Use UnmanagedUser in more places
Closes #2360

[FIX] Crash on opening members list

---

Rocket.Chat/Controllers/Chat/MessagesListViewController.swift

[FIX] Realm write operations outside write transaction

---

Rocket.Chat/Extensions/UIColorExtension.swift
Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.swift
Rocket.Chat/Theme/Theme.swift
Rocket.Chat/Theme/ThemeableViews.swift
Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
Rocket.Chat/Views/Subscriptions/ServersListView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift

[NEW] Add border to all new components attachments/boxes

---

Rocket.Chat/Controllers/Auth/AuthNavigationController.swift
Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
Rocket.Chat/Controllers/Auth/CASViewController.swift
Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Rocket.Chat/Controllers/Auth/LegalTableViewController.swift
Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Rocket.Chat/Controllers/Auth/OAuthViewController.swift
Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
Rocket.Chat/Controllers/Auth/SAMLViewController.swift
Rocket.Chat/Controllers/Auth/SignupCustomFieldsTableViewController.swift
Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
Rocket.Chat/Controllers/Auth/TwoFactorAuthTableViewController.swift
Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
Rocket.Chat/Storyboards/Auth.storyboard
Rocket.Chat/Theme/NotThemeableViews.swift
Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.swift
Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.swift
Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.swift
Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.swift

[FIX] Disable theming in onboarding views

---

Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
Rocket.Chat/Models/Mapping/MessageModelMapping.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift

[IMPROVEMENT] Quoted Attachment improvements

---

Rocket.Chat/Views/Cells/Chat/Info/MemberCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib

[BUG] Color not being applied to text attachments

---

Podfile.lock
Pods/Manifest.lock
Pods/Pods.xcodeproj/project.pbxproj
Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift

[CHORE] Update SDK to fix the app build

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift

[FIX][RCVC] Autocompletion dimming chat without hints

---

README.md

[DOCS] Add a "Reviewed by Hound" badge

---

Rocket.Chat/Controllers/Chat/MessagesViewModel.swift

[CRASH] Fixed a crash with invalid Realm thread

---

Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib

[CHORE] Make image and video components size be based on screen's proportion

---

Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift

Fix attachment sorting bug reported by @geekgonecrazy o/

[FIX] Attachment sorting

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Update app version to 3.2 (222)

---

Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings

Did you missed me? 😛
Translated the remaining strings. 😁
If there's some strings that aren't translated, it's because i don't find a proper translation to it.
Basically, if you don't see `// TODO` in the front of the string, consider it ready for production.
🎉 

[I18N] Update Localizable.strings

---

Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Rocket.Chat/Controllers/Chat/MessagesViewControllerReplying.swift

Closes #1563 
I'm still looking into custom emojis, but it's a being a bit difficult to reuse our logic from textview to labels.
It will be another PR for that.

[IMPROVEMENT] Show emojis and markdown in reply/quote popup

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
Rocket.Chat/Extensions/Models/SubscriptionPermalink.swift
Rocket.Chat/Models/Message/MessageReply.swift
Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/it.lproj/Localizable.strings
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings
Rocket.ChatTests/Extensions/Models/SubscriptionPermalinkSpec.swift
Rocket.ChatTests/Models/MessageSpec.swift

[NEW] Copy message permalink

---

Rocket.Chat/Resources/it.lproj/Localizable.strings

Please review italian translation for all the recently added strings

[I18N] Add new translations for italian strings

---

Rocket.Chat.ShareExtension/Resources/zh-Hans.lproj/Localizable.strings
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/External/RCEmojiKit/zh-Hans.lproj/RCEmojiKit.strings
Rocket.Chat/Resources/zh-Hans.lproj/InfoPlist.strings
Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
Rocket.Chat/Resources/zh-Hans.lproj/VoiceOver.strings

Thanks to Simon, who sent me the files! :-)

[I18N] Add Chinese Simplified language support to the app

---

Rocket.Chat/Resources/it.lproj/Localizable.strings

Translated a couple of strings in italian, for video calls

[I18N] Translate italian strings for video calls

---

Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib

[FIX] Read receipts missing on the list of messages

---

Rocket.Chat/Views/Chat/ChatTitleView.swift
Rocket.Chat/Views/Chat/ChatTitleView.xib

[CHORE] Replace DM icon by bubble on titleView

---

Pods/Pods.xcodeproj/project.pbxproj
Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
Rocket.Chat/Controllers/Chat/MessagesViewControllerUploading.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
Rocket.Chat/Managers/Uploader/UploadManager.swift
Rocket.Chat/Theme/ThemeableViews.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
Rocket.Chat/Views/Cells/Hints/TextHintEmojiViewCell.swift
Rocket.Chat/Views/Cells/Hints/TextHintLabelCell.swift
Rocket.Chat/Views/Cells/Hints/UserHintAvatarViewCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift

[CHORE] Remove unused code, resolve some SwiftLint warnings & suppress couple.

---

Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift

[FIX] View models deallocation & Subscription object mapping fixing on updates

---

Rocket.Chat/Controllers/Auth/LoginTableViewController.swift

[FIX] Fixed color into forgot password button

---

Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift

[FIX] Fixed issue on connecting to a server & having an invalid server after all in some edge cases

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Views/Chat/New Chat/Cells/MessageVideoCallCell.swift

[CHORE] Disable Video/Audio call (CallKit) in China region

---

Rocket.Chat.ShareExtension/Resources/zh-Hant.lproj/Localizable.strings
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/External/RCEmojiKit/zh-Hant.lproj/RCEmojiKit.strings
Rocket.Chat/Resources/zh-Hant.lproj/InfoPlist.strings
Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
Rocket.Chat/Resources/zh-Hant.lproj/VoiceOver.strings

Add Traditional Chinese (zh-TW) translation file.

[NEW] Add Traditional Chinese (zh-TW) translation file

---

Rocket.Chat/Models/User/User.swift

[IMPROVEMENT] Support authentication parameters on avatars

---

Rocket.Chat/Controllers/Directory/DirectoryViewController.swift
Rocket.Chat/Controllers/Directory/DirectoryViewModel.swift
Rocket.Chat/Views/Directory/DirectoryFiltersView.swift

[IMPROVEMENT] Better task management on Directory

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Rocket.Chat/Controllers/Directory/DirectoryViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Managers/AnalyticsManager.swift
Rocket.ChatTests/Models/UserSpec.swift

[CHORE] Add events to Directory & Audio Messages

---

Rocket.Chat.ShareExtension/Resources/pl.lproj/Localizable.strings
Rocket.Chat/External/RCEmojiKit/pl.lproj/RCEmojiKit.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings

[i18n] Add missing polish translations

---

Rocket.Chat/Resources/cs.lproj/Localizable.strings
Rocket.Chat/Resources/de.lproj/Localizable.strings
Rocket.Chat/Resources/el.lproj/Localizable.strings
Rocket.Chat/Resources/en.lproj/Localizable.strings
Rocket.Chat/Resources/es.lproj/Localizable.strings
Rocket.Chat/Resources/fr.lproj/Localizable.strings
Rocket.Chat/Resources/it.lproj/Localizable.strings
Rocket.Chat/Resources/ja.lproj/Localizable.strings
Rocket.Chat/Resources/pl.lproj/Localizable.strings
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Rocket.Chat/Resources/ru.lproj/Localizable.strings
Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings

[IMPROVEMENT] Adjust wording of Members in Directory

---

Podfile.lock
Pods/Manifest.lock
Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist

[CHORE] Update SDK with haptic feedback working again

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat/Info.plist
Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift

[CHORE] UI adjustments on the list of chats

---

Rocket.Chat/Resources/el.lproj/Localizable.strings

Please find latest greek translation updates

[I18N] Greek translation update 2019-03-30

---

Rocket.Chat/Models/Subscription/Subscription.swift

[FIX] Auth params into channel avatar URL

---

Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift

Thanks @luismachado for the fix, this is just an adjustment on the changes of your PR!
Closes #2573

[FIX] User is loosing roles on mapping lastMessage

---

Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib

[CHORE] UI adjustments on quotes & replies

---

Rocket.Chat.ShareExtension/Compose/SEComposeHeaderViewModel.swift
Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.ShareExtension/Rooms/SERoomCellModel.swift
Rocket.Chat/Info.plist

[FIX] ShareExtension references to Discussion

---

Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
Rocket.Chat/Extensions/UIViewController/UIViewControllerExtension.swift

[NEW] Crop image before uploading avatar

---

Rocket.Chat/Controllers/Chat/MessagesViewModel.swift

[FIX] Don't group message with different alias

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Requests/Threads/ThreadFollowRequest.swift
Rocket.Chat/API/Requests/Threads/ThreadMessagesRequest.swift
Rocket.Chat/API/Requests/Threads/ThreadUnfollowRequest.swift
Rocket.Chat/API/Requests/Threads/ThreadsListRequest.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Rocket.Chat/Controllers/Threads/ThreadsViewController.swift
Rocket.Chat/Info.plist
Rocket.Chat/Models/Message/UnmanagedMessage.swift
Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Rocket.Chat/Storyboards/Subscriptions.storyboard
Rocket.Chat/Views/Chat/New Chat/Cells/ThreadReplyCollapsedCell.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsDirectoryHeaderView.swift

- Allow user to fetch thread information on the flow;
- Add docs links into the API requests;
- Fixed theming in some parts of the app and more;
- Fixed many bugs on threads;

[IMPROVEMENT] Adjustments on Threads implementation

---

Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.swift

[FIX] Remove server selection and indicator for whitelabels

---

Rocket.Chat/AppDelegate.swift
Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
Rocket.Chat/Managers/AppManager.swift
Rocket.Chat/Storyboards/Auth.storyboard

Disable the screen that has community login and connect to server button.
- Disables on logout
- Disables if the user is unauthenticated
Jumps straight to connecting....

[FIX] Disable welcome screen for whitelabels

---

Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Controllers/Threads/ThreadsViewController.swift

No idea why this just happens in release... And why this fixes it... But here it goes.
Closes #2710

[FIX] Messages list not displaying correctly in release build

---

Rocket.Chat/Controllers/Chat/MessagesListControllerSearch.swift
Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Rocket.Chat/Extensions/Models/MessageExtensions.swift
Rocket.Chat/Resources/cs.lproj/VoiceOver.strings
Rocket.Chat/Resources/de.lproj/VoiceOver.strings
Rocket.Chat/Resources/el.lproj/VoiceOver.strings
Rocket.Chat/Resources/en.lproj/VoiceOver.strings
Rocket.Chat/Resources/es.lproj/VoiceOver.strings
Rocket.Chat/Resources/fr.lproj/VoiceOver.strings
Rocket.Chat/Resources/it.lproj/VoiceOver.strings
Rocket.Chat/Resources/ja.lproj/VoiceOver.strings
Rocket.Chat/Resources/pl.lproj/VoiceOver.strings
Rocket.Chat/Resources/pt-BR.lproj/VoiceOver.strings
Rocket.Chat/Resources/pt-PT.lproj/VoiceOver.strings
Rocket.Chat/Resources/ru.lproj/VoiceOver.strings
Rocket.Chat/Resources/zh-Hans.lproj/VoiceOver.strings
Rocket.Chat/Resources/zh-Hant.lproj/VoiceOver.strings
Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Rocket.Chat/Views/Chat/ChatTitleView.swift
Rocket.Chat/Views/Chat/ChatTitleView.xib

[NEW] Searching through direct messages VoiceOver accessible - Project 04 

---

Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconCell.swift
Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewController.swift
Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewModel.swift
Rocket.Chat/Resources/cs.lproj/VoiceOver.strings
Rocket.Chat/Resources/de.lproj/VoiceOver.strings
Rocket.Chat/Resources/el.lproj/VoiceOver.strings
Rocket.Chat/Resources/en.lproj/VoiceOver.strings
Rocket.Chat/Resources/es.lproj/VoiceOver.strings
Rocket.Chat/Resources/fr.lproj/VoiceOver.strings
Rocket.Chat/Resources/it.lproj/VoiceOver.strings
Rocket.Chat/Resources/ja.lproj/VoiceOver.strings
Rocket.Chat/Resources/pl.lproj/VoiceOver.strings
Rocket.Chat/Resources/pt-BR.lproj/VoiceOver.strings
Rocket.Chat/Resources/pt-PT.lproj/VoiceOver.strings
Rocket.Chat/Resources/ru.lproj/VoiceOver.strings
Rocket.Chat/Resources/zh-Hans.lproj/VoiceOver.strings
Rocket.Chat/Resources/zh-Hant.lproj/VoiceOver.strings
Rocket.ChatTests/Preferences/AppIcon/ChangeAppIconViewModelSpec.swift

Added the VoiceOver accessibility for the channel icons.

[NEW] Channel icons VoiceOver accessible

---

Rocket.Chat/API/Requests/General/InfoRequest.swift
Rocket.ChatTests/API/Requests/General/InfoRequestSpec.swift

[HOTFIX] Fix info request parsing wrong format when authenticated

---

Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/API/Requests/Emoji/CustomEmojiRequest.swift
Rocket.Chat/API/Requests/Emoji/CustomEmojiRequestOld.swift
Rocket.Chat/Managers/Model/CustomEmojiManager.swift
Rocket.ChatTests/API/Requests/Emoji/CustomEmojiRequestSpec.swift

[CHORE] Update CustomEmojiRequest to new endpoint & use old one as fallback

---

Rocket.Chat.ShareExtension/Info.plist
Rocket.Chat.xcodeproj/project.pbxproj
Rocket.Chat/Info.plist
Rocket.Chat/Resources/cs.lproj/InfoPlist.strings
Rocket.Chat/Resources/de.lproj/InfoPlist.strings
Rocket.Chat/Resources/el.lproj/InfoPlist.strings
Rocket.Chat/Resources/en.lproj/InfoPlist.strings
Rocket.Chat/Resources/es.lproj/InfoPlist.strings
Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
Rocket.Chat/Resources/it.lproj/InfoPlist.strings
Rocket.Chat/Resources/ja.lproj/InfoPlist.strings
Rocket.Chat/Resources/pl.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
Rocket.Chat/Resources/zh-Hans.lproj/InfoPlist.strings
Rocket.Chat/Resources/zh-Hant.lproj/InfoPlist.strings

[CHORE] Bump version to 3.5.2 and fix App Store issue
