- Rocket.Chat.iOS.xcodeproj/project.pbxproj
- Rocket.Chat.iOS/AppDelegate.swift
- Rocket.Chat.iOS/Base.lproj/LeftMenu.storyboard
- Rocket.Chat.iOS/Base.lproj/Main.storyboard
- Rocket.Chat.iOS/DarwinNotifications.swift
- Rocket.Chat.iOS/ViewControllers/AccountBarViewController.swift
- Rocket.Chat.iOS/ViewControllers/AccountOptionsTableViewController.swift
- Rocket.Chat.iOS/ViewControllers/Auth/LoginViewController.swift
- Rocket.Chat.iOS/ViewControllers/ViewController.swift
This is so the user can set his status. What I 've done is this:
User can choose his status from the left menu. When the user press home or switches to another app the status remains the same. But when the user locks the device the status is set to away. When he unlocks, the status is set back to the previous status.If he puts the app to the background and then locks the device the the status stays the same. Also when the status is changed from the web client the app get's notified and the status is synced to the device. I added an observer to AccountBarViewController but I noticed that it gets plenty notifications so every time we close the left menu the observer is removed to keep network traffic low. It's being added every time we open the left menu. If it's needed later it won't be …
> Setting User's Status (Working and Synced with the web client)

- Rocket.Chat.iOS.xcodeproj/project.pbxproj
- Rocket.Chat.iOS/AppDelegate.swift
- Rocket.Chat.iOS/Base.lproj/LaunchScreen.storyboard
- Rocket.Chat.iOS/Base.lproj/LeftMenu.storyboard
- Rocket.Chat.iOS/Base.lproj/Main.storyboard
- Rocket.Chat.iOS/Base.lproj/Right.storyboard
- Rocket.Chat.iOS/ChatMessage.swift
- Rocket.Chat.iOS/DarwinNotifications.swift
- Rocket.Chat.iOS/HistoryTableViewCell.swift
- Rocket.Chat.iOS/Room.swift
- Rocket.Chat.iOS/ViewControllers/AccountOptionsTableViewController.swift
- Rocket.Chat.iOS/ViewControllers/Auth/AuthViewController.swift
- Rocket.Chat.iOS/ViewControllers/ChatsNavTableViewController.swift
- Rocket.Chat.iOS/ViewControllers/LeftViewController.swift
- Rocket.Chat.iOS/ViewControllers/ViewController.swift
Now the channels in the left menu are showing. You can switch between rooms. When entering the settings now you can go back by selecting a room or by selecting a status. When you close the app completely it remembers the last room you have joined and next time loads that channel again. When you switch to a different room it scrolls down to the latest message. For now when you start the app and it loads the room give it some time to load it and then change room. If you change to another room before it loads the current room the app crashes. This will be fixed by adding a loading screen.
Also after talking with @Sing-Li I switched the subscription from messages to stream-messages in order to get the chat messages.
Please feel free to review and provide any feedback...
> Room selection in left menu and changed the subscription to stream-messages

- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
If long pressed on text view in message cell, the gesture event will not be sent to cell's delegate correctly as follows.
> Fix: Long press on message cell should be responded by message cell delegate

- Rocket.Chat/Controllers/MainViewController.swift
- Rocket.Chat/Managers/Model/AuthManager.swift
> Persist auth data & recover it case DB gets corrupted or destroyed

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/MainViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Extensions/Models/MessageExtensions.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Managers/Model/AuthManager.swift
- Rocket.Chat/Managers/Model/AuthSettingsManager.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
- Rocket.Chat/Managers/Uploader/UploadManager.swift
- Rocket.Chat/Models/AuthSettings.swift
- Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
- Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
- Rocket.Chat/Models/Mapping/UserModelMapping.swift
- Rocket.Chat/Models/Subscription.swift
- Rocket.Chat/Models/User.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
- Rocket.Chat/Views/Chat/ChatPreviewModeView.swift
- Rocket.Chat/Views/Chat/ChatTitleView.swift
- Rocket.ChatTests/Managers/AuthSettingsManagerSpec.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
- Rocket.ChatTests/Models/UserSpec.swift
Closes #543
**When `UI_Use_Real_Name == true`**
- Every part of the app that uses `Subscription` model will display `fname` property;
- Every part of the app that uses `User` model will display `name` property;
**When `UI_Use_Real_Name == false`**
- Every part of the app that uses `Subscription` model will display `name` property;
- Every part of the app that uses `User` model will display `username` property;
> [NEW] Honor UI_Use_Real_Name settings to show user full name or username all over the app

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Closes #578 
This PR fixes a crash when the index isn't available in `groupInfomation` array.
> [FIX] Crash on Subscriptions list on headerView section

- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Managers/Model/AuthSettingsManager.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
Fixes warnings and errors:
1. Fix generics optional error issue in "MessageCompletionObject" closure
2. Optimizes "for if" conditions to "for where"
3. Fixes NotificationCenter observer removal warnings of self on view disappear
Closes #542
> Fix general warnings and errors in Xcode 9

- Rocket.Chat/Managers/Model/SubscriptionManager.swift
Closes #626 
When server is configured to use user's real name instead of username, the search on Spotlight wasn't saving the `fname` property in Subscription instance.
> [FIX] User's full name in spotlight search as well

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
Closes #642 
Updates weren't happening because the controller would check if the user was searching and would pause the updates.
I removed the checks and started filtering the incoming updates.
> [FIX] Update subscriptions while searching

- Rocket.Chat/Controllers/Chat/MainChatViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Closes #645 
Also noticed the cancel button doesn't remove the text and reset the search after pressing like the web version, so i fixed that too.
> [FIX] Show cancel button if search not empty + reset text when pressed

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Closes #655 
Simply calling the search function again after clearing the text does the job.
> [FIX] Reset search after cancel pressed

- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Closes #665 
Text rendering can do some different stuff between devices. iPhone SE and Plus require an additional pixel to render some wrapped texts correctly.
> [FIX] Text wrapping on iPhone SE and Plus

- Rocket.Chat/Controllers/Chat/ChatViewController.swift
Closes #673
Every time a new message is appended in the collection view, a method is called. The method completion was nil and now it set a new offset value to the collection view.
> [FIX] Temp message and text field spacing

- Podfile.lock
Crashlytics on Rocket.Chat.iOS reported many crashes.
Some of this was found to be a conflict between the parsing of links and image links and it's been fixed in 3.0.3
> [CHORE] Update RCMarkdownParser to 3.0.3 (fix crashes)

- Rocket.Chat/Models/AuthSettings.swift
- Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
- Rocket.Chat/Models/Subscription.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
Closes #615
I implemented the settings parameter to allow room names with special chars.
TODO:
> [NEW] Room names with special chars

- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/MainViewController.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Managers/Launcher/NetworkCoordinator.swift
- Rocket.Chat/Managers/NetworkManager.swift
- Rocket.ChatTests/Managers/NetworkManagerSpec.swift
Closes #692 
This PR avoids starting the app without knowing the networking state and prevents from adding the same Message twice... since the `append` method is executed in background, we were experiencing this issue in some rare cases.
> [FIX] Fixed some networking (check when the app starts) and scrolling issues

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Models/User.swift
- Rocket.ChatTests/Models/UserSpec.swift
> [FIX] Make sure empty user's name returns username instead when setting is enabled

- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Managers/Model/MessageManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
> [NEW] Add "user is typing" view when some user is typing

- Rocket.Chat/API/API.swift
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.ChatTests/Extensions/NSURLExtensionSpec.swift
Closes #744
I replaced the 'demo.rocket.chat' occurrences to 'open.rocket.chat'.
> [CHORE] Migrate 'demo.rocket.chat' references to 'open.rocket.chat'

- Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
- Rocket.Chat/Managers/Uploader/Helpers/UploadVideoCompression.swift
Also changed the encoding to mpeg4, so it's now possible to view the videos in other clients (changing the extension wasn't enough)
Closes #754
> [FIX] Video receiving wrong extension when uploading

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsPageViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Storyboards/Subscriptions.storyboard
- Rocket.ChatTests/Managers/AppManagerSpec.swift
Closes #610 
This PR allows anyone to have a **static** URL into the app by simply having a new setting **RC_SERVER_URL** into *Info.plist* file of the app. Example:
> **Info.plist**
> RC_SERVER_URL = "https://open.rocket.chat"
It also removes the multi-server feature when the app is complied with a static URL.
> [NEW] Support "static" URL into the app

- Podfile
- Podfile.lock
- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatControllerDocuments.swift
- Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
- Rocket.Chat/Extensions/DataExtension.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.xib
Some improvements to SDWebImage seem to fix #856.
I also had to [update our SimpleImageViewer](https://github.com/cardoso/SimpleImageViewer/pull/1) to support the new way SDWebImage renders GIFs.
I will merge the pod's branch and update this if we approve this change.
> [FIX] Large GIF files causing crashes

- Podfile
- Podfile.lock
You can join #ios_crash_test in open.rocket.chat to test this.
Closes #854 
Closes #816
> [FIX] Alternate link markdown crashes

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Managers/DraftMessageManager.swift
- Rocket.Chat/Managers/Model/AuthManager.swift
- Rocket.ChatTests/Managers/DraftMessageManagerSpec.swift
Closes #859
@rafaelks I've addressed your suggestion to have a new class to handle the caching, take a look at `DraftMessageManager`. I tried to follow the same structure you applied in `MessageTextCacheManager` but with a struct and static functions.
Also I've added a `clearServerDraftMessages` function that runs on logout to avoid keeping data from servers that are not active anymore on the device.
What do you think about this approach?
> [NEW] Save message drafts per chat

- Rocket.Chat/Controllers/Chat/ChatDataController.swift
Closes #931 
This solved lots of redundant calls we were having:
```swift
if obj.message?.text != message.text {
MessageTextCacheManager.shared.update(for: message)
}
```
Sometimes some metadata is updated, but doesn't mean the text is :)
> [IMPROVEMENT] Highlight performance

- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
- Rocket.Chat/Managers/MessageTextCacheManager.swift
- Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
Closes #939
This improves the performance greatly by not hanging the application while the text is being parsed.
I've tested this **A LOT** in a device and in the simulator and it seems to be working fine :)
I had to modify the highlight methods to not access realm models (Message, etc)
Things to test:
* Large markdown and highlighted texts
* Editing messages (on the web)
* Sending messages
* Receiving messages
TODO:
> [IMPROVEMENT] Parse markdown and highlights in background thread

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Requests/Message/PostMessageRequest.swift
- Rocket.ChatTests/API/Requests/Message/PostMessageRequestSpec.swift
- Rocket.ChatTests/Models/MessageSpec.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
This PR adds the REST API abstraction for sending messages
> [NEW] Send messages via REST API

- Rocket.Chat/Controllers/Auth/AuthViewController.swift
This fixes any issues that can happen when the server closes the socket before giving a response.
Closes #974 
Closes #975
> [FIX] Handle edge connection lost cases on authentication

- Rocket.Chat/Managers/PushManager.swift
- Rocket.ChatTests/Managers/PushManagerSpec.swift
This feature allows the user to reply to a message from a notification without having to enter the App. (iOS 10 capability)
Will only work in Rocket.Chat servers with 0.60.0 or above.
Here's an instance for testing: https://unstable.rocket.chat
Closes #831
> [NEW] Allow replying in notification (Quick Reply)

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Requests/Message/PostMessageRequest.swift
- Rocket.Chat/Extensions/API/APIExtensions.swift
- Rocket.Chat/Managers/PushManager.swift
- Rocket.ChatTests/API/Requests/Message/PostMessageRequestSpec.swift
We were looking for the subscription in the old realm, so only the second time worked.
Now the REST call is not depending on the current realm to get the roomId.
> [HOTFIX] Notification reply not working first time if it's not from last server

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Storyboards/Subscriptions.storyboard
> [FIX] Rooms names cutting off if using larger text (accessibility)

- Rocket.Chat.xcodeproj/project.pbxproj
Fixes CocoaPods' warning about ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES.
> [CHORE] fix cocoapods warning about ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Extensions/Models/UserExtensions.swift
- Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
Now it's very close to what the web version does.
- Begin with only a '@' and limit results to 5 + here and all at the end.
- Latest message senders appear first
- Filter username by contains and not begins with
Closes #176
TODO:
> [IMPROVEMENT] Improve mention autocompletion

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/API/Requests/Message/SendMessageRequest.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
- Messages are confirmed faster now and should be more reliable.
- Only works on servers > 0.60.0, otherwise we fallback to the old WebSocket method.
Testable on: https://unstable.rocket.chat
Closes #830 
Closes #473
> [NEW] Send messages via HTTP + WebSockets fallback

- Rocket.Chat/Extensions/DateExtension.swift
- Rocket.ChatTests/API/Clients/CommandsClientSpec.swift
Just a formatting problem.
Fixes every message that comes from REST API:
Pinned and starred messages, sent messages in 0.60.0
Closes #1059
> [FIX] Some dates showing as UTC

- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Helpers/ChatCollectionViewFlowLayout.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Managers/MessageTextCacheManager.swift
- Rocket.Chat/Managers/Model/AuthSettingsManager.swift
- Rocket.Chat/Managers/Model/MessageManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager.swift
- Rocket.Chat/Models/Base/ModelMappeable.swift
- Rocket.Chat/Models/Subscription.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
- Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
- Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift
Closes #1064 
This PR fixes a few performance and bugs in the app:
1. ImageView flickering on the messages list;
2. Cell was being reused hundreds of times on any Message update call from Realm;
3. Moved the Markdown processing to the main thread again, to avoid weird behaviors;
> [CHORE] Improve the performance of the app, reducing calls on main-thread and the number of reutilization of the cells

- Rocket.Chat/Models/Mapping/MessageModelMapping.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Reactions/ReactionListView.swift
- Rocket.Chat/Views/Reactions/ReactionListView.xib
Hotfix: this only happens on testflight
Fixes:
- reaction views not being removed from superview
- last reaction not clearing from message object when all reactions are removed
> [HOTFIX] Some layout fixes for reactions

- Rocket.Chat/de.lproj/Localizable.strings
Old label overflowed the width, so some characters were cut off. We need no word by word match of the translations, so this message should be sufficient: "The server must support SSL"
@rafaelks suggested a multiline label and adjusting the width of the label to fit the `textFieldServerURL`.
> [I18N] Shorter ssl required expression

- Rocket.Chat/Controllers/Auth/AuthViewController.swift
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
This fixes:
- weird warning when going back from authentication screen to connection screen #1144 
- close button not working in connection screen
- being able to press back button after authenticating (could cause bugs)
Closes #1144
> [FIX] Some authentication screen bugs

- Rocket.Chat/Managers/PushManager.swift
- Rocket.Chat/cs.lproj/Localizable.strings
- Rocket.Chat/de.lproj/Localizable.strings
- Rocket.Chat/en.lproj/Localizable.strings
- Rocket.Chat/fr.lproj/Localizable.strings
- Rocket.Chat/pl.lproj/Localizable.strings
- Rocket.Chat/pt-BR.lproj/Localizable.strings
Although we have no other option on mobile and thus just show the keyboard to reply instantly, on Watch we see the "Reply" action button
> [I18N] Translate quick reply

- Rocket.Chat/Views/Avatar/AvatarView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
Closes #1206 
(I think we still may have some issue when user first connect to a server, but then the issue isn't related to the SDWebImage loading, but our cell reutilization).
I also added some new settings to reduce the memory usage for large images. Important to our list fo messages with large attachments. 👍
> [IMPROVEMENT] Sometimes the attachment wasn't loading at first

- Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
We were using the wrong view as bounds and source
> [HOTFIX] EmojiPicker on iPad not displaying properly

- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionListView.xib
Closes #1181
The bug was happening because the constraints were using Safe Area and for some reason the iOS 10 wasn't making fallback... so I changed the constraints to a fixed height (30px) and centred vertically.
> [FIX] Reaction size on iOS 10.x

- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
`chat.edit_mode` is not used anywhere
> [i18n] Remove unused localize string

- Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
You can reproduce the crash on open with ":party_parrot: ::::"
I'm not sure if it's the same crash, because XCode doesn't report the same callstack, but it's pretty bad too.
Closes #1289
> [FIX] Crashing with certain messages with custom emojis

- Rocket.Chat/External/RCEmojiKit/Emojione.swift
- Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
- Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
This was preventing emoji shortnames like : +1 : from being parsed correctly.
> [HOTFIX] Escape regex characters in emoji shortnames before parsing

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Views/Chat/KeyboardFrameView.swift
- The text input bar no longer lags 1 frame behind the keyboard.
- Should have better performance characteristics, since the new implementation is only called when the frame of the keyboard actually changes (unlike previously, where the method was called inside `scrollViewDidScroll`)
> [IMPROVEMENT] Interactive keyboard dismissal improved

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Auth/AuthViewController.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
- Rocket.Chat/Managers/Model/AuthManager.swift
- Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Now we can see information such as user id, real name, email and server URL on the crash report as the screen shot below shows:
Closes #1437
> [CHORE] Add more information on crash of Crashlytics

- Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
- Rocket.Chat/External/RCEmojiKit/Emojione.swift
- Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
- Rocket.Chat/Managers/MessageTextCacheManager.swift
- Rocket.Chat/Models/CustomEmoji.swift
Reverts some changes made in #1390 
One of the problems is we can't make a generic regex because not everything inside :colons: is a valid emoji.
> [HOTFIX] App hanging on emoji parsing sometimes

- Rocket.Chat/API/Clients/CommandsClient.swift
- Rocket.Chat/API/Clients/InfoClient.swift
- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/Controllers/Auth/AuthViewController.swift
- Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
- Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
- Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Extensions/Models/UserExtensions.swift
- Rocket.Chat/Extensions/RealmExtension.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/Model/AuthManager.swift
- Rocket.Chat/Managers/Model/AuthSettingsManager.swift
- Rocket.Chat/Managers/Model/CustomEmojiManager.swift
- Rocket.Chat/Managers/Model/LoginServiceManager.swift
- Rocket.Chat/Managers/Model/MessageManager.swift
- Rocket.Chat/Managers/Model/PermissionManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager.swift
- Rocket.Chat/Models/Auth.swift
- Rocket.Chat/Models/Base/BaseModel.swift
- Rocket.Chat/Models/CustomEmoji.swift
- Rocket.Chat/Models/Subscription.swift
- Rocket.Chat/Models/User.swift
- Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
- Rocket.ChatTests/Models/BaseModelSpec.swift
We were performing write operations on async operations pointing to the `current` instance of Realm. The issue is: if we make a network operation for the "Server A" containing a realm operation on its callback, then switch to the "Server B" the callback would get data from "Server A" but would try to write it on "Server B" realm instance because it would be the `current` one. 
I just started capturing the `current` realm before the network/async operation and then using this reference to execute any instruction contained on the operation's callback.
Closes #1462
> [FIX] Crash when alternating servers 

- Rocket.Chat/API/APIRequest.swift
- Rocket.Chat/Extensions/URLExtension.swift
- Rocket.ChatTests/Models/AuthSpec.swift
A few weeks ago I've posted a change that introduced support for Rocket.Chat hosted on subdirectory (https://github.com/RocketChat/Rocket.Chat.iOS/pull/1277). Next day, @filipealva posted a fix that actually broken my patch but unblock him due to slash at the end of the `api.host` (https://github.com/RocketChat/Rocket.Chat.iOS/pull/1415). It resulted in a whole path replacement instead of applying requested path to the end of the host address!
There are four cases where Rocket.Chat could be hosted and where `/api/v1/me` should point to:
- `https://instance.com` -> `https://instance.com/api/v1/me`
- `https://instance.com/` -> `https://instance.com/api/v1/me`
- `https://instance.com/rocket` -> `https://instance.com/rocket/api/v1/me`
- `https://instance.com/rocket/` -> …
> [FIX] Build URL that may use subdirectory

- Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
- Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
When I got the issue, I plugged my device on Xcode and noticed that the URL being used to connect to the WebSocket wasn't in a WebSocket format.
> [BUG] Random Invalid Session after upgrading sometimes

- Rocket.Chat/Controllers/Chat/MainChatViewController.swift
- Rocket.Chat/Managers/Socket/Response/SocketError.swift
It seems that the socket is now sending the status code for an invalid session error (`"403"`) when we were expecting the following string: `"error-invalid-user"`. 
Closes #1404
> [FIX] Handle invalid session

- Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/Chat/MainChatViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Managers/AppManager.swift
Some interesting information about the impact of this improvement. Note that these benchmarks are not meant to be exact information, they're just some information I could collect when simulating the same session before and after this fix. The steps of my test session: switch 30 times between servers then try to scroll up the messages on a busy channel (I made the tests using the same servers and the same channels). 
- Usage peak: 177%
- It took about 3 min for me to switch between the servers 30 times due to the performance loss
- Usage peak: 104%
- It took about 1:30 min for me to switch between the servers 30 times (it's visibly smoothier 👌 )
- Allocated memory after the tests: 224MB
- Allocated memory after the tests: 127MB
- Received 10,4MB during the tests
- Sent …
> [IMPROVEMENT] Remove retain cycles on core chat hierarchy

- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
Since we already had problems caused by holding strong references on `connectionHandlers` I decided to refactor `connectionHandlers` from `Dictionary` to `NSMapTable` which is able to store weak references. 
Although `NSMapTable` lets the objects to be released from memory automatically it doesn't happen as fast as if we manually clear the references, so keep in mind that if you need to deallocate the references stored on `connectionHandlers` immediately to do a heavy operation (such as switching to another server) you better clear it manually to avoid performance issues older devices. 
Closes #1568
> [IMPROVEMENT] Holding core chat references when adding a new server

- Podfile.lock
`<https://a.b|a<b>>`
Before:
After:
This may be related to a crash we have currently. Let's see if this fixes it 🙂
> [CHORE] Update RCMarkdownParser (fix alt link parsing)

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
- Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
- Rocket.Chat/Controllers/Chat/MembersListViewController.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Views/ActionSheets/UserActionSheetPresenter.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
- Rocket.Chat/Views/Chat/RCTextView.swift
- Instead of just opening the direct message without prompting the user, now we show an action sheet.
- Also fixes real name/username not displaying according server settings in member cells. (used in members list and reactions)
Preview images:
iPhone:
> [IMPROVEMENT] Show action sheet when tapping usernames, mentions, etc

- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Models/Message/MessageReply.swift
Issue: if you enter in a room and send a message, where this message should be sequential, the message won't be sequential until you send another one and the layout breaks. This was happening because the last message of the dataset was an invisible unread marker.
Now, when you enter in a room and send a message, if the message needs to be sequential, it will be just fine.
> [FIX] Logic on sending sequencial messages when the screen appears

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Requests/Subscription/SubscriptionFilesRequest.swift
- Rocket.Chat/API/Requests/Subscription/SubscriptionRolesRequest.swift
- Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
- Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
- Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
- Rocket.Chat/Controllers/Chat/ChatControllerRolesController.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Extensions/Models/MessageExtensions.swift
- Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/Model/AuthManager/AuthManagerCurrentUser.swift
- Rocket.Chat/Models/Base/ModelMappeable.swift
- Rocket.Chat/Models/File.swift
- Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
- Rocket.Chat/Models/Mapping/UserModelMapping.swift
- Rocket.Chat/Models/Role.swift
- Rocket.Chat/Models/Subscription/Subscription.swift
- Rocket.Chat/Models/User/User.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.xib
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.ChatTests/API/Requests/Subscription/SubscriptionRolesRequestSpec.swift
- Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
- Rocket.ChatTests/Models/MessageSpec.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
> [NEW] Add support to Broadcast rooms

- Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
> [FIX] Use other mapping from REST requests on "lastSeen" field

- Rocket.Chat/Extensions/URLExtension.swift
- Rocket.ChatTests/Extensions/URLExtensionSpec.swift
For some reason, URL(string:) urls.like.this:3000 means scheme = "urls.like.this", host = nil 🤔
> [FIX] Some urls not receiving implicit https on connection

- Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
- Removed whitespaces at the beginning of a message. 
- Newlines replaced with a single space.
Done to prevent situations similar to the one shown in the screengrab.
> [IMPROVEMENT] Removed whitespaces at the beginning of a message.

- Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
Was removed in a pervious commit by me.
The text currently reads "Yousent an attachment"
> [FIX] Added a space before the "sent an attachment" text

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/Views/Subscriptions/ServersListView.swift
Fixes the incorrect inset for server list view on iOS 10. 
A `frameForDropDownOverlay` property has been added to `SubscriptionsViewController`, so that that same changes can be easily applied to `SubscriptionsSortingView` (#1737).
> [FIX] Fix server list view frame on iOS 10

- Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
- Rocket.Chat/Storyboards/Preferences.storyboard
If the device did not support changing the app icons, the last option from the first section of the preferences tableview controller would be hidden, which in this case was the preference for setting the default web browser.
To fix this behavior, I have moved the app icon preference to last in the list.
This is just a hot fix, an improved implementation should be worked on later.
> [HOTFIX] Fix for web browser preference getting hidden instead of the app icon preference if the device does not support changing app icons.

- Rocket.Chat/Controllers/Auth/AuthTableViewControllerAuthenticationHandler.swift
- Rocket.Chat/Controllers/Auth/LoginTableViewControllerAuthenticationHandler.swift
This crash happens because when we authenticate we persist  `AuthSettings` object, on the first time it happens we are persisting an unmanaged object, so there's no problem. But, when we authenticate, then navigate to 2FA screen, then get back and authenticate again, our `serverPublicSettings` object is not unmanaged anymore, and since we delete all `AuthSettings` objects before persisting a new one we wind up removing the object we are about to add again, so `Realm` says that we are trying to persist an invalidated object. Besides this issue, this process would cause a threading issue with `Realm` as well. 
My first thought was to approach the two `Realm` issues, but then I wondered why we are persisting  `AuthSettings` after authenticating the user if we already have …
> [CRASH] 2FA auth crashing when popped

- Rocket.Chat/AppDelegate.swift
- Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
- Rocket.Chat/Managers/WindowManager.swift
- Rocket.Chat/Storyboards/Auth.storyboard
To reproduce:
1. Create an account on `open.rocket.chat` but don't set a username (close the window when prompted to) 
2. Log in on the iOS app using the e-mail and password, but don't set a username. 
3. Close the app.
4. Open it again
Before this fix it would authenticate the user even without a username, now it will always check if there's a username and if not it will show the register username screen.
It also fixes a bug that used to allow the user to set an empty username.
Closes #1764
> [BUG] Authenticating without username

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Auth/AuthNavigationController.swift
- Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Controllers/Auth/LegalTableViewController.swift
- Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
- Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
- Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
- Rocket.Chat/Controllers/Base/BaseNavigationController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
- Rocket.Chat/Storyboards/Auth.storyboard
- Rocket.Chat/Theme/ThemeableViews.swift
This also addresses an issue where the nav bar would get colored the same as the background color of the chat view controller when the user is editing a message.
An `AuthNavigationController` has been added since all the changes required to the navigation controller for the new on boarding are not generic and do not belong in the `BaseNavigationController`
Closes #1820 
Closes #1821
Closes #1781
> [FIX] Transparent nav bar and reactors list headers

- Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoCellProtocol.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
`ChannelInfoDescriptionCell` now uses `UITableViewAutomaticDimension` rather than a constant height.
Closes #1882
> [FIX] Channel description becomes smaller with longer length

- Rocket.Chat/Managers/NotificationManager.swift
- Rocket.Chat/Models/ChatNotification.swift
- Rocket.ChatTests/Managers/NotificationManagerSpec.swift
- Rocket.ChatTests/Models/ChatNotificationSpec.swift
This PR fixed a crash caused due to some code being called on a background thread, which really should only be called on the main thread.
- In-app notifications not posting/visible.
- In-app notifications stay on screen, and cannot be dismissed.
Closes #1939
> [FIX] Crash due to in-app notifications

- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
- Rocket.Chat/Extensions/API/APIExtensions.swift
- Rocket.Chat/Managers/Model/CustomEmojiManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
- Rocket.Chat/Views/Subscriptions/ServersListView.swift
- Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
This issue is very hard to reproduce. I'm not sure if this PR really fixes the issue or just make it harder to reproduce. We may need to rethink the entire way that we deal with the isolation of the databases. Just trusting in the "selected" doesn't work well when dealing with async calls (and we have A LOT of async calls that interact with the database on the callback). In the ideal world, we would have to think on how to make each call know which database/server it belongs to.
Closes #1903
> [BUG] Attempt to fix a database inconsistency and some minor improvements on the server switching process

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/AppDelegate.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Managers/ShortcutsManager.swift
- Rocket.Chat/Resources/cs.lproj/InfoPlist.strings
- Rocket.Chat/Resources/de.lproj/InfoPlist.strings
- Rocket.Chat/Resources/el.lproj/InfoPlist.strings
- Rocket.Chat/Resources/en.lproj/InfoPlist.strings
- Rocket.Chat/Resources/es.lproj/InfoPlist.strings
- Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
- Rocket.Chat/Resources/pl.lproj/InfoPlist.strings
- Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
- Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
- Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
- Rocket.ChatTests/Managers/ShortcutsManagerSpec.swift
Closes #833
Added servers so far. Can add more types of shortcuts later on.
Do we want anything else except servers? Maybe channels and DMs? But since we are kinda limited with the number of shortcuts, we would need a good algorithm to determine which to shows - rather not the latest since it might be a little bit confusing (often) showing different shortcuts each time.
> [FEATURE] Add Home Screen Quick Actions

- Rocket.Chat.ShareExtension/Info.plist
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
- Rocket.Chat/Helpers/RealmAssorter.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Managers/NotificationManager.swift
- Rocket.Chat/Models/ChatNotification.swift
- Rocket.Chat/Views/Avatar/AvatarView.swift
- Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
- Rocket.ChatTests/Managers/NotificationManagerSpec.swift
- Rocket.ChatTests/Models/ChatNotificationSpec.swift
Depends on #1937 
This PR removes the whole processing data on Realm, that's showing in the screenshots below. The processing of data with huge amount of data on low-end iPhones were causing freezes.
> [CHORE] Remove the object lookups on Realm updates & increase a lot the performance of the app

- Rocket.Chat/Storyboards/Preferences.storyboard
Icon's borde was clipped:
After the fix:
> [BUX] Fix clipped application icon's border on changing icon screen

- Rocket.Chat/Views/Avatar/AvatarView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
This crash happened only twice times and for a single jaibroken device. In one of the cases it has only 4% of RAM available and in another it was running the app in background when it happened.
After testing it and figuring it out that the device conditions may be the cause of this crash I decided to just add the missing `super.prepareForReuse` call and revert any other change that I made to possibly fix this crash.
We'll monitor it and if it wind up happenning with other devices and users we will investigate. 
Closes #1989
> [CRASH] Fatal Exception: NSInternalInconsistencyException Only run on the main thread!

- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/DatabaseManager.swift
Closes #1991
Closes #1993
(Look at the last message, it shows when we use the wrong cached settings then it hides when we fetch the correct settings from the server)
> [FIX] Server isolation issues

- Rocket.Chat/Views/Chat/RCTextView.swift
There is currently an issue while using a deep press (3d touch) on links that may cause them to open twice. This PR fixes it as well as replaces deprecated method od `UITextViewDelegate`.
> [BUG] Replace deprecated method and fix interaction with deep press

- Rocket.Chat/Controllers/User/UserDetail/UserDetailTableView.swift
- Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
Takes into account size of  table view content now
| Before | After |
| ------ | ----- |
| ![](https://i.imgur.com/pSLBmRJ.jpg) | ![](https://i.imgur.com/jBQsRfE.jpg) |
> [IMPROVEMENT] UserDetail popover sizing on iPad

- Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
- Rocket.Chat/Storyboards/Chat.storyboard
> [BUG] Hide login button when setting is disabled

- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.xib
- Rocket.Chat/Storyboards/Subscriptions.storyboard
- Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
> [CHORE] Bouncing reactors & badge all the time for unreads

- Rocket.Chat/Controllers/Base/BaseTableViewController.swift
- Rocket.Chat/Controllers/Base/BaseViewController.swift
- Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
- Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
- Rocket.Chat/Theme/ThemeableViews.swift
- Rocket.Chat/Views/Subscriptions/ServersListView.swift
- Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
- Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Theming popovers should now be easier. It's still not completely automatic, for performance reasons, but all that is required is to call applyTheme in `layoutSubviews` for a `UIView` or `viewDidLayoutSubviews` in a `UIViewController`.
The popovers now have a higher contrast with the background of the presenting view.
Closes #2022
> [IMPROVEMENT] Improve theming popovers

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Currently, the table view cells for `SubscriptionsViewController` have a transparent background when they are selected. This causes the cells to flicker when they are reloaded.
This will solve the flickering issue, without the need of `UIView.performWithoutAnimation`, which may also be responsible for a crash we recently started experiencing.
Possibly Closes #2036 
This issue can be closed after beta testing, or a public release, if the crash no longer occurs.
> [IMPROVEMENT] Use opaque cells for subscriptions table view

- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
- Rocket.Chat/Models/Base/BaseModel.swift
- Rocket.Chat/Views/Avatar/AvatarView.swift
- Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
- Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
- Rocket.Chat/Views/Chat/ChatTitleView.swift
- Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
As we discovered while investigating this crash actually is composed of a lot of different issues that triggers a fatal exception on realm. This PR solves all the occurrences of this crash that are still active after the release 3.0.
Closes #2037
> [CRASH] RLMObject_Private.hpp line 45 ___ZN12_GLOBAL__N_115makeBoxedGetterIN5realm10

- Podfile.lock
- Adds a semi-transparent square behind close button
- Single tap shows/hides close button
- Adds safe area for better layout in iPhone X
Preview: https://imgur.com/nu0y2Fr
Work was done in this commit: https://github.com/cardoso/SimpleImageViewer/commit/8222c338de0f285ca0c2d556c5d8dedd4a365b52
Closes #1810
> [IMPROVEMENT] Prevent fullscreen white image from obscuring close button & fix iPhone X layout

- Rocket.Chat/Managers/PushManager.swift
Replying to a notification was not working in this specific case.
1. App is in background
2. It's in another server
3. You try to reply to a notification from a server different from the one currently selected
> [FIX] Notification reply not working when app is open and in other server

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
This is reproducible by:
1. Putting App in small size on multitasking
2. Entering a room
3. Making App Fullscreen
- Loses control and navigation bar of right side
- Left-side works like iPhone
Closes #2031
> [FIX] iPad losing right-side controller after becoming fullscreen on multitasking

- Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
It was opening a modal with no close button or back button.
> [FIX] Not being able to close reactor list in iPad compact mode

- Rocket.Chat.ShareExtension/Base/SENavigationController.swift
- Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
- Rocket.Chat.ShareExtension/State/SEStore.swift
- Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift
- Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
- Remove warnings
- Use natural animation (`UIViewAnimationOptions(rawValue: 7 << 16)`)
- Support interactive keyboard dismissal
- Empty search bar does not filter results
- Tapping cancel on the search bar no longer dismisses the share extension 
Closes #2084
> [IMPROVEMENT] Improve Share Extension usability

- Rocket.Chat.ShareExtension/State/SEState.swift
> [FIX] Filter hidden rooms from share extension

- Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.xib
- Rocket.Chat/Theme/ThemeableViews.swift
> [FIX] Background color for the search bar in EmojiPicker

- Rocket.Chat/Models/User/UserPermissions.swift
This was causing admins to not be able to post in read only channels they did not create.
> [FIX] Not taking server roles into account in room context

- Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
- Rocket.Chat/Controllers/Preferences/Profile/StatusTableViewController.swift
- Rocket.Chat/Managers/AnalyticsManager.swift
> [CHORE] Add events for "New Workspace" & "Status Update"

- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/PushManager.swift
> [BUG] Quick reply adds new chat view

- Rocket.Chat/Models/Auth/AuthCanDeleteMessage.swift
- Rocket.Chat/Models/Auth/AuthCanEditMessage.swift
- Rocket.Chat/Models/Auth/AuthCanPinMessage.swift
> [FIX] Message actions not taking into account room roles

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
- Rocket.Chat/Controllers/Chat/ChatDataController.swift
- Rocket.Chat/Extensions/Models/ObjectExtension.swift
- Rocket.Chat/Managers/DraftMessageManager.swift
- Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerTyping.swift
- Rocket.Chat/Managers/Socket/SocketManager.swift
- Rocket.Chat/Models/Attachment.swift
- Rocket.Chat/Models/Base/BaseModel.swift
- Rocket.Chat/Models/User/UserUtils.swift
> [CRASH] Fatal Exception: RLMException Object has been deleted or invalidated

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Scripts/Localize.swift
I used this script: https://github.com/freshOS/Localize
But made some changes:
- Don't error with unused strings because we build some in runtime
- Don't report possible untranslated strings because we have many 'TODOs'
It will report missing and duplicate strings
Closes #972
> [CHORE] Add script to validate localizable strings files

- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/PushManager.swift
If you put the App in background in server A and receive notification from server B and tap it, the App will open in the correct server but not in the correct room.
> [FIX] Not opening correct room after tapping notification when in other server

- Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
- Rocket.Chat/Managers/Socket/Response/SocketError.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
Fixes
- Some UI code was being called in background
- Bad UI strings
- Bad error handling when email already exists
Closes #2160
> [FIX] Fix some problems with registration

- Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
> [CRASH] Fixed crash on reusing cells for Auth controller

- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/API/Requests/Room/RoomMembersRequest.swift
- Rocket.Chat/Controllers/Chat/MembersListViewController.swift
- Rocket.Chat/Models/Mapping/UserModelMapping.swift
- Rocket.Chat/Models/User/UserPermissions.swift
Closes #2163
Also reported here: https://forums.rocket.chat/t/app-create-channel-fail/1952.
This one was really hard to find, but the problem was happening is: on getting the response from the API, we were simply overriding all the user data (in consequence, removing all the roles). I changed to simply update the results and create a new one only if needed.
> [FIX] Roles would be cleaned on viewing the list of Members

- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/ja.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Views/Buttons/StyledButton.swift
This was a decision we made internally for both iOS and Android to avoid users getting automatically connected to our community server. Now the user will be forced to enter an URL in order to connect.
> [IMPROVEMENT] Remove defaults to open.rocket.chat & add a new placeholder to the connection field

- circle.yml
Circle CI does not support iOS 11.3 on the Xcode 10.0.0 images.
> [CI] Use iOS 11.2 in place of 11.3 for circle CI

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
> [NEW] Image component

- Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Enabled clearButton at the TextField inside the Alert that is presented on forgotPasswordPressed action at LoginTableViewController.
Closes #2162
> [IMPROVEMENT] Enabled clearButton on the email TextField at ForgotPassword

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
> [IMPROVEMENT] Invalidate collection view layout on screen rotation

- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
- Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
- Rocket.Chat/Extensions/RealmCurrent.swift
- Rocket.Chat/Extensions/RealmExecute.swift
- Rocket.Chat/Managers/Launcher/TestingCoordinator.swift
- Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
- Rocket.Chat/Models/Message/UnmanagedMessage.swift
- Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
- Rocket.ChatTests/API/Clients/CommandsClientSpec.swift
- Rocket.ChatTests/API/Clients/InfoClientSpec.swift
- Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
- Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
- Rocket.ChatTests/API/Requests/Message/ReactMessageRequestSpec.swift
- Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
- Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
- Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
- Rocket.ChatTests/Managers/MessageManagerSystemMessageSpec.swift
- Rocket.ChatTests/Managers/PermissionManagerSpec.swift
- Rocket.ChatTests/Models/Auth/AuthSpec.swift
- Rocket.ChatTests/Models/CustomEmojiSpec.swift
- Rocket.ChatTests/Models/MessageSpec.swift
- Rocket.ChatTests/Models/UserSpec.swift
> [CHORE] Resolve couple code warnings in the project

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
- Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
This pull-request resolves couple of issues:
1. Load initial messages partially from database instead of all messages. Right now it's loading 30 messages every page;
2. It loads paginated result from database as well instead;
> [IMPROVEMENT] DataController fetching partial database messages and code improvements

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseFileMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
Add support to message headers for the following attachments:
- File
- Text Attachment (with fields)
- Image Attachment
> [NEW] Attachments supporting message headers

- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
This PR includes the following changes:
1. Move most of the data processing to the background thread;
2. Organize files & methods in the right position;
3. Only process the day markers and sequential once per data update; Also make the verifications in the whole dataset to make sure there's no duplicated separators;
**WARNING: There's still stuff being processed on the main thread and the CollectionView is being updated with animations, we'll resolve this problems in another PR.**
> [IMPROVEMENT] Move data processing to the background, organize better the file and fixed many bugs related to the data control

- Rocket.Chat/Managers/MessageTextCacheManager.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
Now the theme is cached with the message to avoid repeated work. This allows us to not force update the message every time `applyTheme` is called.
> [IMPROVEMENT] Chat theming performance

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Extensions/UIColorExtension.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.xib
- Rocket.Chat/Views/Chat/New Chat/ChatItems/UnreadMarkerChatItem.swift
This PR adds support to unread marker on the list and also marks the subscription as read when view appear.
> [NEW] Add support to "Unread Marker" on the list of messages

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/ChatViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Extensions/UIColorExtension.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
- Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.xib
- Rocket.Chat/Views/Chat/New Chat/ChatItems/UnreadMarkerChatItem.swift
- Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
- This PR adds the properties related to loaders & headers to the view model;
- Also includes tests that covers most of the properties normalized from the view model;
**First needs to merge #2262**
> [NEW] Add support to Headers & Loaders to the View Model & much more tests

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionListView.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
> [NEW] Components interspacing

- Podfile.lock
- Pods/Manifest.lock
- Pods/RocketChatViewController/Composer/Classes/Addons/Hints/HintsView.swift
- Pods/RocketChatViewController/Composer/Classes/Addons/Hints/TextHintCell.swift
- Pods/RocketChatViewController/Composer/Classes/Addons/Hints/UserHintCell.swift
- Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
- Pods/RocketChatViewController/RocketChatViewController/Classes/UIKitExtension.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
- Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
- Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
- Rocket.Chat/Models/User/UnmanagedUser.swift
- Rocket.Chat/Models/User/User.swift
- Rocket.Chat/Models/User/UserUtils.swift
- Rocket.Chat/Views/Avatar/AvatarView.swift
- Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
- Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
- Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
This pull-request was suppose to fix the empty cells, but I still didn't figure out what's happening (still investigating, but will send another PR once this is fixed). For now, this one includes:
- Removed all managed objects from AvatarView;
- Reduced the complexity of AvatarView to rely only in one String and one URL object;
- Prepare another page from database after loading one page from scrolling to the top and present it;
- Changed the size of the page to 10 on scrolling and 30 on first page and pre-fetched page;
- Changed the method being used to start pagination to scrollView delegate instead of UICollectionView method (willDisplay:);
> [IMPROVEMENT] Performance improvements, code simplification & prefetch one more page from database

- Podfile.lock
- Pods/Local Podspecs/RocketChatViewController.podspec.json
- Pods/Manifest.lock
- Pods/RocketChatViewController/Composer/Classes/Addons/Hints/TextHintCell.swift
- Pods/RocketChatViewController/Composer/Classes/Addons/Hints/UserHintCell.swift
- Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
This update includes fixes for invalid indexPaths and small code improvements.
> [CHORE] Update RocketChatViewController to reflect latest fixes

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
> [FIX][RCVC] Reintroduce iPad chat empty state

- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
> [CHORE] Use dataSorted to calculate cell's size

- Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Helpers/ShortcutHelpers.swift
> [NEW][RCVC] Reintroduce all shortcuts & message searching

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSectionExtension.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
- Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
- Rocket.Chat/Extensions/UIColorExtension.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/ReactionsChatItem.swift
> [NEW] Add back reactions handler, fix missing delegate reference and more

- Rocket.Chat/Managers/OAuthManager.swift
- Rocket.ChatTests/Managers/OAuthManagerSpec.swift
> [FIX] Include path in OAuth callback url building

- Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
This PR changes the fixed constraints without taking consideration the margin to actually take and reduce the current space from left & right margins.
Now the avatar is aligned with "back button" and the message is aligned with the composer text view.
> [IMPROVEMENT] Change from fixed constraints to relative ones

- Rocket.Chat/Models/Message/UnmanagedMessage.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/it.lproj/Localizable.strings
- Rocket.Chat/Resources/ja.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/AudioMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseTextAttachmentChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/BasicMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/SequentialMessageChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
- Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
> [CHORE] Support empty title & alias on the message

- Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
> [FIX] Adjust missing constraint in TextAttachmentCell.xib

- Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
- Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
- Rocket.Chat/Storyboards/Auth.storyboard
- Rocket.Chat/Theme/ThemeableViews.swift
- Rocket.Chat/Views/Buttons/StyledButton.swift
- Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.xib
- Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
- Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.xib
- Rocket.Chat/Views/TextFields/StyledTextField.swift
This pull-request fixes issues caused by my changes on themes for #2348 and also add supports to Dynamic Type in all of the authentication flow.
> [IMPROVEMENT] Fixes & support to Dynamic Type on all auth flow

- Rocket.Chat/AppDelegate.swift
- Rocket.Chat/Managers/AppManager.swift
- Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
- Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
> [CHORE] Remove user from crash reports 

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
- Rocket.Chat/Managers/UserReviewManager.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
- Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
Awkward solution, but seems to work well.
Closes #2329
> [FIX] Composer disappearing after app store review

- Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
- Rocket.Chat/Controllers/Auth/AuthTableViewControllerLoginServices.swift
- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
This crash is caused due to a nil serverURL when loading an AuthTableViewController. I couldn't reproduce it, so I took some actions that will prevent this crash from happening on any given scenario:
- Stop forcing unwrap of `AuthTableViewController` and `LoginTableViewController` serverURL properties  
- Stop recomputing the url property from `ConnectViewController` at the time of injecting it into Auth or Login screens. Instead of doing that I just used the stored version of the URL that we set right after connecting and validating it, i.e. it will never be nil if the connection is working properly.
Closes #2385
> [CRASH] AuthTableViewController.swift line 128 AuthTableViewController.viewDidLoad()

- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
> [BUG] Fixed problem with unread marker wrongly positioned

- Rocket.Chat/API/Requests/General/PermissionsRequest.swift
- Rocket.ChatTests/API/Clients/InfoClientSpec.swift
- Rocket.ChatTests/API/Requests/General/PermissionsRequestSpec.swift
Closes #2425
New endpoint of the API now returns the permissions inside a `permissions` array.
> [FIX] Permissions API changed format on new endpoint

- Rocket.Chat.ShareExtension/Info.plist
- Rocket.Chat/Info.plist
- Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
> [CHORE] Adjust spacing from basic message to other messages

- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/API/Requests/Message/DeleteMessageRequest.swift
- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
> [BUG][RCVC] Deleted messages are not removed from the list

- Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
- Rocket.Chat/Models/Message/UnmanagedMessage.swift
Part of solving this bug was to make sure that `data` and `dataSorted` were aligned with `messagesQuery`. The way we are doing it today can generate data races in some edge cases, and these data races may make us to lose some update yet. 
In other words: the bug is fixed 💯 but we need to optimize the way we sync our "data pipeline" to avoid side effects caused by data races
Closes #2434
> [BUG] Mishandling message websocket updates

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerTyping.swift
- Rocket.Chat/Helpers/Throttle.swift
> [FIX][REGRESSION] Not sending typing event

- Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesSizingManager.swift
- Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.swift
- Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
- Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.swift
- Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.swift
- Rocket.ChatTests/Controllers/MessagesSizingViewModelSpec.swift
Fixes a crash happening on iOS 11 devices, wasn't able to reproduce the issue but figured a way to prevent this from happening again (and updated tests for it).
> [FIX] Do not return NaN values or negative values from the sizing manager

- Rocket.Chat/Helpers/MessageTextFontAttributes.swift
> [FIX] Issues with Dynamic Typing being different than expected

- Rocket.Chat/Extensions/UIImageExtension.swift
Closes #2200 
I decided to go low-level on this one, since sharing screenshots from iOS apparently sets a limit of 120MB of RAM, and the method we were using was reaching 120MB easily with any screenshot, causing the extension to crash.
More info can be found [here](https://nshipster.com/image-resizing/).
> [FIX] Use Accelerate framework to resize UIImage in order to use much less memory for the share extension

- Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
- Rocket.Chat/Storyboards/Auth.storyboard
Closes #2477 
This PR address the issue of the `UITextField` in the connect screen not behaving as expected, where the cursor jumps to the end of the text when editing in the middle of the text.
This problem was mainly caused by the delegate method `shouldChangeCharactersIn` where the whole text was replaced with every edit. I noticed that this was primarily to trigger the `textFieldDidChange()` method to toggle the connect button. 
My solution was to instead add a listener to the textField for whenever a change was detected, and the handler function being the same `textFieldDidChange()` method. As a result the `shouldChangeCharactersIn` method is unused and I have removed it.
Hope my solution is ideal for the problem. Please let me know if there are any changes needed to …
> [IMPROVEMENT] Add editing changed handler to UITextField in connect screen

- Rocket.Chat/API/Clients/MessagesClient.swift
- Rocket.Chat/API/Clients/SpotlightClient.swift
- Rocket.Chat/API/Clients/SubscriptionsClient.swift
- Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
- Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
- Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerRooms.swift
- Rocket.Chat/Managers/Socket/Response/ResponseMessage.swift
- Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
- Rocket.Chat/Models/Base/ModelHandler.swift
- Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
- Rocket.Chat/Models/Message/UnmanagedMessage.swift
- Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
- Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
- Rocket.ChatTests/API/Requests/Room/RoomHistoryRequestSpec.swift
- Rocket.ChatTests/Extensions/NSAttributedStringExtensionsSpec.swift
> [FIX] Fixed issues with duplicated subscription or missing on the list

- Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
- Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
- Rocket.Chat/Models/Mapping/MessageModelMapping.swift
- Rocket.Chat/Models/Message/Message.swift
- Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/it.lproj/Localizable.strings
- Rocket.Chat/Resources/ja.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
> [CHORE] Remove the feature to block users locally from the app

- Rocket.Chat.xcodeproj/project.pbxproj
- Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
- Rocket.Chat/Models/Subscription/Subscription.swift
- Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
- Rocket.Chat/Resources/cs.lproj/Localizable.strings
- Rocket.Chat/Resources/de.lproj/Localizable.strings
- Rocket.Chat/Resources/el.lproj/Localizable.strings
- Rocket.Chat/Resources/en.lproj/Localizable.strings
- Rocket.Chat/Resources/es.lproj/Localizable.strings
- Rocket.Chat/Resources/fr.lproj/Localizable.strings
- Rocket.Chat/Resources/it.lproj/Localizable.strings
- Rocket.Chat/Resources/ja.lproj/Localizable.strings
- Rocket.Chat/Resources/pl.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
- Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
- Rocket.Chat/Resources/ru.lproj/Localizable.strings
- Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
- Rocket.Chat/Views/Chat/ChatAnnouncementView.swift
- Rocket.ChatTests/Models/SubscriptionSpec.swift
Closes #1593.
Two main additions to the application:
1. Announcement can be seen on `ChannelActionsView` as one of the channel's information. Placed between Description and Topic, similar to the desktop client.
2. Announcement can also be seen on the main chat view pinned to the top as a banner, similar to the desktop client as well. Implemented as a new `UIView` class, `ChatAnnouncementView`. This banner will follow the colour scheme of the current active theme, with the background being `bannerBackground` and label text `auxiliaryText`. 
Light theme - iPhone XS Max
Dark theme - iPad Pro 12.9 inch (Please ignore the test channels... :P)
Black theme - iPhone SE (also a deliberately long announcement to see the text formatting when the label overflows the screen.)
Lastly, I …
> [NEW] Support announcements

- Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
- Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
- Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
> [CHORE] Remove @ from file attachments, autocomplete & quotes

- Rocket.Chat.ShareExtension/Info.plist
- Rocket.Chat/Controllers/Chat/MessagesViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/Info.plist
- Rocket.Chat/Models/Subscription/Subscription.swift
- Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
> [BUG] New DMs after searching user are not getting created via API

- Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
**Problem** - After selecting a status in the Profile, `popviewcontroller()` pops the top view controller from the navigation stack _before_ the statusValueLabel be updated.
Before - 
I came up with two solutions - 
- `viewDidAppear()` instead of `viewWillAppear()`
- add a delay using `DisplayQueue.main.asyncafter()` when popping the top view controller.
After (using the former solution) -
Closes #2075
> [FIX] Status not updated immediately after selecting

- Rocket.Chat/Managers/WebBrowserManager.swift
> [NEW] Try to open links as an universal URL instead of directly on the browser

- Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Closes #2530 
No hints will be generated if it is detected that the word containing the "/" character is not the first word.
Screenshots after fix:
> [IMPROVEMENT] Auto suggesting slash commands even when not first character

- Rocket.Chat/Controllers/Preferences/Notifications/NotificationsChooseCell.swift
- Rocket.Chat/Helpers/Dynamic.swift
Clear listeners for dynamic value in notifications before setting them again
Reloading cells caused multiple listeners to be registered which had a huge impact on performance and might cause other issues
> [FIX] Clear listeners for dynamic value in notifications

- Rocket.Chat/Theme/ThemeableViews.swift
Closes #2577 
Added the bezel.view = white, so that the view is visible in dark and black themes.
Before / After :
> [IMPROVEMENT] Change theme for MBProgressHUD

- Rocket.Chat/Views/Chat/ChatTitleView.swift
- Rocket.Chat/Views/Chat/ChatTitleView.xib
- Rocket.ChatTests/Views/Chat/ChatTitleViewSpec.swift
> [IMPROVEMENT] Allow scrolling of chat title if it doesn’t fit

- Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
- Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPickerController.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
- Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
- Rocket.Chat/External/RCEmojiKit/pl.lproj/RCEmojiKit.strings
Closes #2423 
I have refactored `EmojiPickerViewController` a little bit since there were a few issues with it (like calling a `super` of `loadView` - it should never be called while subclassing directly from `UIViewController`).
Moved presenter-related code to 'iPad only' since it was causing leaks on iPhones.
Please, double-check my changes since it was kinda tricky and not sure if it's the best solution.
NOTE: All tests succeed locally on my machine.
> [FIX] Refactor EmojiPickerViewController and fix memory leak on iPhone

- Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
Tiny fix - Safe Layout Guide in ChatPreviewModeView.
Closes #2628
> [FIX] "Join Channel" button overlapping home bar on iPhone X/Xr/Xs/Max 

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Closes #2631 
Tiny fix, but solved the navigation bar disappearing.
But, while solving it, I found another bug. 
The "Type a message" Composer View is missing. 
Edit - It is a keyboard dismissal bug. Working on it.
> [FIX] Navigation bar disappears after subscription search

- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Tiny fix to make the background colour in long swipe gesture same.
Closes #2230
> [IMPROVEMENT] Swipe to read messages with uniform colour

- Rocket.Chat/Models/CustomEmoji.swift
> [FIX] Prevent CustomEmoji image URL double url escaping

- Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
- Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
- Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
- Rocket.Chat/Resources/cs.lproj/VoiceOver.strings
- Rocket.Chat/Resources/de.lproj/VoiceOver.strings
- Rocket.Chat/Resources/el.lproj/VoiceOver.strings
- Rocket.Chat/Resources/en.lproj/VoiceOver.strings
- Rocket.Chat/Resources/es.lproj/VoiceOver.strings
- Rocket.Chat/Resources/fr.lproj/VoiceOver.strings
- Rocket.Chat/Resources/it.lproj/VoiceOver.strings
- Rocket.Chat/Resources/ja.lproj/VoiceOver.strings
- Rocket.Chat/Resources/pl.lproj/VoiceOver.strings
- Rocket.Chat/Resources/pt-BR.lproj/VoiceOver.strings
- Rocket.Chat/Resources/pt-PT.lproj/VoiceOver.strings
- Rocket.Chat/Resources/ru.lproj/VoiceOver.strings
- Rocket.Chat/Resources/zh-Hans.lproj/VoiceOver.strings
- Rocket.Chat/Resources/zh-Hant.lproj/VoiceOver.strings
- Rocket.Chat/Storyboards/Preferences.storyboard
> [NEW] Preferences / editing profile VoiceOver accessible - Project 05

- Rocket.Chat/API/Requests/General/InfoRequest.swift
- Rocket.ChatTests/API/Clients/InfoClientSpec.swift
- Rocket.ChatTests/API/Requests/General/InfoRequestSpec.swift
- Rocket.ChatTests/Managers/Requests/InfoRequestHandlerSpec.swift
The info endpoint `/api/v1/info` had been deprecated, and now removed with v2.0.0 release of Rocket.Chat . 
This PR changes the request to use the `/api/info` endpoint, introduced in place of the old one. 
PR: https://github.com/RocketChat/Rocket.Chat/pull/15197
Doc: https://rocket.chat/docs/developer-guides/rest-api/miscellaneous/info/
> [FIX] Update info request to use the /api/info endpoint
